[[item]]
id = 3
key = "coin_1"
unit = "piece"
shelf_life_minutes = 0
bulk = { width = 1, height = 1 }

[[item]]
id = 4
key = "coin_2"
unit = "piece"
shelf_life_minutes = 0
bulk = { width = 1, height = 1 }

[[item]]
id = 5
key = "coin_5"
unit = "piece"
shelf_life_minutes = 0
bulk = { width = 1, height = 1 }

[[item]]
id = 6
key = "note_10"
unit = "piece"
shelf_life_minutes = 0
bulk = { width = 1, height = 1 }

[[item]]
id = 7
key = "note_20"
unit = "piece"
shelf_life_minutes = 0
bulk = { width = 1, height = 1 }

[[item]]
id = 8
key = "note_50"
unit = "piece"
shelf_life_minutes = 0
bulk = { width = 1, height = 1 }
