// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  locationId: __t.u64().primaryKey().name("location_id"),
  actorKind: __t.u32().name("actor_kind"),
  actorId: __t.u64().name("actor_id"),
  chunkKey: __t.u64().name("chunk_key"),
  floor: __t.i8(),
});
