// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  cadence: __t.u32().primaryKey(),
  lastTargetAt: __t.timestamp().name("last_target_at"),
  lastFiredAt: __t.timestamp().name("last_fired_at"),
  fires: __t.u64(),
  missed: __t.u64(),
});
