// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  transitionId: __t.u64().primaryKey().name("transition_id"),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  targetX: __t.i32().name("target_x"),
  targetY: __t.i32().name("target_y"),
  targetFloor: __t.i8().name("target_floor"),
  chunkKey: __t.u64().name("chunk_key"),
});
