// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  characterId: __t.u64().primaryKey().name("character_id"),
  chunkKey: __t.u64().name("chunk_key"),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  fracX: __t.u8().name("frac_x"),
  fracY: __t.u8().name("frac_y"),
  updatedAt: __t.timestamp().name("updated_at"),
});
