// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  areaId: __t.u64().primaryKey().name("area_id"),
  roomId: __t.u64().name("room_id"),
  x0: __t.i32().name("x_0"),
  y0: __t.i32().name("y_0"),
  x1: __t.i32().name("x_1"),
  y1: __t.i32().name("y_1"),
  floor: __t.i8(),
  chunkKey: __t.u64().name("chunk_key"),
});
