// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BudgetReviewSchedule = __t.object("BudgetReviewSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type BudgetReviewSchedule = __Infer<typeof BudgetReviewSchedule>;

export const Building = __t.object("Building", {
  buildingId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Building = __Infer<typeof Building>;

export const BuildingArea = __t.object("BuildingArea", {
  areaId: __t.u64(),
  buildingId: __t.u64(),
  x0: __t.i32(),
  y0: __t.i32(),
  x1: __t.i32(),
  y1: __t.i32(),
  floor: __t.i8(),
  chunkKey: __t.u64(),
});
export type BuildingArea = __Infer<typeof BuildingArea>;

export const Character = __t.object("Character", {
  characterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Character = __Infer<typeof Character>;

export const CharacterIdentity = __t.object("CharacterIdentity", {
  mappingId: __t.u64(),
  identity: __t.identity(),
  characterId: __t.u64(),
});
export type CharacterIdentity = __Infer<typeof CharacterIdentity>;

export const Citizen = __t.object("Citizen", {
  citizenId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Citizen = __Infer<typeof Citizen>;

export const CitizenState = __t.object("CitizenState", {
  citizenId: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type CitizenState = __Infer<typeof CitizenState>;

export const CitizenTransitionSchedule = __t.object("CitizenTransitionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CitizenTransitionSchedule = __Infer<typeof CitizenTransitionSchedule>;

export const DemoPing = __t.object("DemoPing", {
  id: __t.u64(),
  message: __t.string(),
  writtenAt: __t.timestamp(),
});
export type DemoPing = __Infer<typeof DemoPing>;

export const EconomySchedule = __t.object("EconomySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EconomySchedule = __Infer<typeof EconomySchedule>;

export const FloorTransition = __t.object("FloorTransition", {
  transitionId: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  targetX: __t.i32(),
  targetY: __t.i32(),
  targetFloor: __t.i8(),
  chunkKey: __t.u64(),
});
export type FloorTransition = __Infer<typeof FloorTransition>;

export const GrowthSchedule = __t.object("GrowthSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GrowthSchedule = __Infer<typeof GrowthSchedule>;

export const LayerCode = __t.object("LayerCode", {
  code: __t.u32(),
  name: __t.string(),
  rank: __t.u32(),
});
export type LayerCode = __Infer<typeof LayerCode>;

export const MaintenanceSchedule = __t.object("MaintenanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSchedule = __Infer<typeof MaintenanceSchedule>;

export const MatterKind = __t.object("MatterKind", {
  code: __t.u32(),
  name: __t.string(),
});
export type MatterKind = __Infer<typeof MatterKind>;

export const MetricsSampleSchedule = __t.object("MetricsSampleSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MetricsSampleSchedule = __Infer<typeof MetricsSampleSchedule>;

export const ModuleOwner = __t.object("ModuleOwner", {
  id: __t.u8(),
  owner: __t.identity(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const NodeKind = __t.object("NodeKind", {
  code: __t.u32(),
  name: __t.string(),
});
export type NodeKind = __Infer<typeof NodeKind>;

export const PlacedObject = __t.object("PlacedObject", {
  objectId: __t.u64(),
  defId: __t.u32(),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  layer: __t.u32(),
  orientation: __t.u8(),
  chunkKey: __t.u64(),
});
export type PlacedObject = __Infer<typeof PlacedObject>;

export const Provision = __t.object("Provision", {
  code: __t.u32(),
  name: __t.string(),
});
export type Provision = __Infer<typeof Provision>;

export const ReasonCode = __t.object("ReasonCode", {
  code: __t.u32(),
  name: __t.string(),
});
export type ReasonCode = __Infer<typeof ReasonCode>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  buildingId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomArea = __t.object("RoomArea", {
  areaId: __t.u64(),
  roomId: __t.u64(),
  x0: __t.i32(),
  y0: __t.i32(),
  x1: __t.i32(),
  y1: __t.i32(),
  floor: __t.i8(),
  chunkKey: __t.u64(),
});
export type RoomArea = __Infer<typeof RoomArea>;

export const WorldClockSchedule = __t.object("WorldClockSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldClockSchedule = __Infer<typeof WorldClockSchedule>;

