// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BudgetReviewSchedule = __t.object("BudgetReviewSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type BudgetReviewSchedule = __Infer<typeof BudgetReviewSchedule>;

export const Building = __t.object("Building", {
  buildingId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Building = __Infer<typeof Building>;

export const BuildingArea = __t.object("BuildingArea", {
  areaId: __t.u64(),
  buildingId: __t.u64(),
  x0: __t.i32(),
  y0: __t.i32(),
  x1: __t.i32(),
  y1: __t.i32(),
  floor: __t.i8(),
  chunkKey: __t.u64(),
});
export type BuildingArea = __Infer<typeof BuildingArea>;

export const Business = __t.object("Business", {
  businessId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Business = __Infer<typeof Business>;

export const CadenceLiveness = __t.object("CadenceLiveness", {
  cadence: __t.u32(),
  lastTargetAt: __t.timestamp(),
  lastFiredAt: __t.timestamp(),
  fires: __t.u64(),
  missed: __t.u64(),
});
export type CadenceLiveness = __Infer<typeof CadenceLiveness>;

export const Character = __t.object("Character", {
  characterId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Character = __Infer<typeof Character>;

export const CharacterIdentity = __t.object("CharacterIdentity", {
  mappingId: __t.u64(),
  identity: __t.identity(),
  characterId: __t.u64(),
  issuerId: __t.u64(),
});
export type CharacterIdentity = __Infer<typeof CharacterIdentity>;

export const Citizen = __t.object("Citizen", {
  citizenId: __t.u64(),
  createdAt: __t.timestamp(),
  appearanceBody: __t.u16(),
  appearanceEyes: __t.u16(),
  appearanceOutfit: __t.u16(),
  appearanceHairstyle: __t.u16(),
  appearanceAccessory: __t.u16(),
});
export type Citizen = __Infer<typeof Citizen>;

export const CitizenState = __t.object("CitizenState", {
  citizenId: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type CitizenState = __Infer<typeof CitizenState>;

export const CitizenTransitionSchedule = __t.object("CitizenTransitionSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type CitizenTransitionSchedule = __Infer<typeof CitizenTransitionSchedule>;

export const ContainerKind = __t.object("ContainerKind", {
  code: __t.u32(),
  name: __t.string(),
});
export type ContainerKind = __Infer<typeof ContainerKind>;

export const DemoPing = __t.object("DemoPing", {
  id: __t.u64(),
  message: __t.string(),
  writtenAt: __t.timestamp(),
});
export type DemoPing = __Infer<typeof DemoPing>;

export const District = __t.object("District", {
  districtId: __t.u64(),
  seed: __t.u64(),
  x0: __t.i32(),
  y0: __t.i32(),
  x1: __t.i32(),
  y1: __t.i32(),
  generationVersion: __t.u32(),
  rngVersion: __t.u32(),
  defsVersion: __t.string(),
  generatedAt: __t.timestamp(),
});
export type District = __Infer<typeof District>;

export const EconomySchedule = __t.object("EconomySchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type EconomySchedule = __Infer<typeof EconomySchedule>;

export const FloorTransition = __t.object("FloorTransition", {
  transitionId: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  targetX: __t.i32(),
  targetY: __t.i32(),
  targetFloor: __t.i8(),
  chunkKey: __t.u64(),
});
export type FloorTransition = __Infer<typeof FloorTransition>;

export const GrowthSchedule = __t.object("GrowthSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GrowthSchedule = __Infer<typeof GrowthSchedule>;

export const HolderKind = __t.object("HolderKind", {
  code: __t.u32(),
  name: __t.string(),
});
export type HolderKind = __Infer<typeof HolderKind>;

export const ItemHeld = __t.object("ItemHeld", {
  instanceId: __t.u64(),
  containerKind: __t.u32(),
  containerId: __t.u64(),
  slotX: __t.u8(),
  slotY: __t.u8(),
  orientation: __t.u8(),
});
export type ItemHeld = __Infer<typeof ItemHeld>;

export const ItemInstance = __t.object("ItemInstance", {
  instanceId: __t.u64(),
  defId: __t.u32(),
  createdAt: __t.timestamp(),
});
export type ItemInstance = __Infer<typeof ItemInstance>;

export const ItemPlaced = __t.object("ItemPlaced", {
  instanceId: __t.u64(),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  offsetX: __t.u8(),
  offsetY: __t.u8(),
  orientation: __t.u8(),
  chunkKey: __t.u64(),
});
export type ItemPlaced = __Infer<typeof ItemPlaced>;

export const LayerCode = __t.object("LayerCode", {
  code: __t.u32(),
  name: __t.string(),
  rank: __t.u32(),
});
export type LayerCode = __Infer<typeof LayerCode>;

export const LinkRequest = __t.object("LinkRequest", {
  requestId: __t.u64(),
  identity: __t.identity(),
  issuerId: __t.u64(),
  code: __t.string(),
  expiresAt: __t.i64(),
});
export type LinkRequest = __Infer<typeof LinkRequest>;

export const MaintenanceSchedule = __t.object("MaintenanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSchedule = __Infer<typeof MaintenanceSchedule>;

export const MatterKind = __t.object("MatterKind", {
  code: __t.u32(),
  name: __t.string(),
});
export type MatterKind = __Infer<typeof MatterKind>;

export const MetricsSampleSchedule = __t.object("MetricsSampleSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MetricsSampleSchedule = __Infer<typeof MetricsSampleSchedule>;

export const ModuleOwner = __t.object("ModuleOwner", {
  id: __t.u8(),
  owner: __t.identity(),
});
export type ModuleOwner = __Infer<typeof ModuleOwner>;

export const ModuleVersion = __t.object("ModuleVersion", {
  defsVersion: __t.string(),
  protocolVersion: __t.string(),
});
export type ModuleVersion = __Infer<typeof ModuleVersion>;

export const MyCharacter = __t.object("MyCharacter", {
  characterId: __t.u64(),
  createdAt: __t.timestamp(),
  linked: __t.bool(),
});
export type MyCharacter = __Infer<typeof MyCharacter>;

export const NodeKind = __t.object("NodeKind", {
  code: __t.u32(),
  name: __t.string(),
});
export type NodeKind = __Infer<typeof NodeKind>;

export const OidcIssuer = __t.object("OidcIssuer", {
  issuerId: __t.u64(),
  issuer: __t.string(),
  clientId: __t.string(),
});
export type OidcIssuer = __Infer<typeof OidcIssuer>;

export const PlacedObject = __t.object("PlacedObject", {
  objectId: __t.u64(),
  defId: __t.u32(),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  layer: __t.u32(),
  orientation: __t.u8(),
  chunkKey: __t.u64(),
});
export type PlacedObject = __Infer<typeof PlacedObject>;

export const Provision = __t.object("Provision", {
  code: __t.u32(),
  name: __t.string(),
});
export type Provision = __Infer<typeof Provision>;

export const ReasonCode = __t.object("ReasonCode", {
  code: __t.u32(),
  name: __t.string(),
});
export type ReasonCode = __Infer<typeof ReasonCode>;

export const ReducerClassCounter = __t.object("ReducerClassCounter", {
  class: __t.string(),
  calls: __t.u64(),
  sampledCalls: __t.u64(),
});
export type ReducerClassCounter = __Infer<typeof ReducerClassCounter>;

export const ReducerClassSample = __t.object("ReducerClassSample", {
  sampleId: __t.u64(),
  sampledAt: __t.timestamp(),
  class: __t.string(),
  callsTotal: __t.u64(),
  callsDelta: __t.u64(),
});
export type ReducerClassSample = __Infer<typeof ReducerClassSample>;

export const RestoreState = __t.object("RestoreState", {
  id: __t.u8(),
  open: __t.bool(),
});
export type RestoreState = __Infer<typeof RestoreState>;

export const Room = __t.object("Room", {
  roomId: __t.u64(),
  buildingId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Room = __Infer<typeof Room>;

export const RoomArea = __t.object("RoomArea", {
  areaId: __t.u64(),
  roomId: __t.u64(),
  x0: __t.i32(),
  y0: __t.i32(),
  x1: __t.i32(),
  y1: __t.i32(),
  floor: __t.i8(),
  chunkKey: __t.u64(),
});
export type RoomArea = __Infer<typeof RoomArea>;

export const Stock = __t.object("Stock", {
  stockId: __t.u64(),
  holderKind: __t.u32(),
  holderId: __t.u64(),
  itemId: __t.u32(),
  quantity: __t.u64(),
});
export type Stock = __Infer<typeof Stock>;

export const StorageSample = __t.object("StorageSample", {
  sampleId: __t.u64(),
  sampledAt: __t.timestamp(),
  totalBytesEst: __t.u64(),
  overReview: __t.bool(),
  overWall: __t.bool(),
  reviewBytes: __t.u64(),
  wallBytes: __t.u64(),
});
export type StorageSample = __Infer<typeof StorageSample>;

export const TableSample = __t.object("TableSample", {
  sampleId: __t.u64(),
  sampledAt: __t.timestamp(),
  tableAccessor: __t.string(),
  rows: __t.u64(),
  bytesEst: __t.u64(),
  alertRows: __t.u64(),
  maxRows: __t.u64(),
  overAlert: __t.bool(),
});
export type TableSample = __Infer<typeof TableSample>;

export const Unit = __t.object("Unit", {
  code: __t.u32(),
  name: __t.string(),
});
export type Unit = __Infer<typeof Unit>;

export const WorldClock = __t.object("WorldClock", {
  id: __t.u8(),
  epochAt: __t.timestamp(),
  speed: __t.u32(),
});
export type WorldClock = __Infer<typeof WorldClock>;

export const WorldClockSchedule = __t.object("WorldClockSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type WorldClockSchedule = __Infer<typeof WorldClockSchedule>;

