//! Quentin's direction: pins that the server's and the client's
//! independent parsers agree on every field, mechanically. This is the
//! Rust side -- reads `sim::generated::defs`'s own compiled tables (what
//! the module actually consumes, no parsing involved) and checks a
//! canonical dump, in the exact same format
//! `client/tests/unit/defs/dump-golden.test.ts` independently produces
//! from the JSON side, against the one committed
//! `fixtures/defs-dump.v1.golden`. Never regenerated by this test; a
//! mismatch is exactly the moment a human must look.

use sim::generated::defs;

const GOLDEN: &str = include_str!("../../../fixtures/defs-dump.v1.golden");

fn canonical_dump() -> String {
    let mut lines: Vec<String> = Vec::new();

    for o in defs::OBJECTS {
        lines.push(format!(
            "object {} id={} height={} width={}",
            o.key, o.id, o.height, o.width
        ));
    }
    for i in defs::ITEMS {
        lines.push(format!("item {} id={}", i.key, i.id));
    }
    for r in defs::RECIPES {
        let mut inputs: Vec<&str> = r.inputs.to_vec();
        inputs.sort_unstable();
        let mut outputs: Vec<&str> = r.outputs.to_vec();
        outputs.sort_unstable();
        lines.push(format!(
            "recipe {} id={} inputs=[{}] outputs=[{}]",
            r.key,
            r.id,
            inputs.join(","),
            outputs.join(",")
        ));
    }
    for p in defs::PROFESSIONS {
        lines.push(format!("profession {} id={}", p.key, p.id));
    }
    for c in defs::CHAINS {
        let mut links: Vec<&str> = c.links.to_vec();
        links.sort_unstable();
        lines.push(format!(
            "chain {} id={} links=[{}]",
            c.key,
            c.id,
            links.join(",")
        ));
    }
    for b in defs::BALANCE {
        lines.push(format!(
            "balance {} value={} min={} max={}",
            b.key, b.value, b.min, b.max
        ));
    }

    lines.sort();
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

#[test]
fn matches_the_shared_golden_both_parsers_are_checked_against() {
    assert_eq!(
        canonical_dump(),
        GOLDEN,
        "sim::generated::defs's own canonical dump moved out of sync with fixtures/defs-dump.v1.golden -- if this is a deliberate defs/ change, client/tests/unit/defs/dump-golden.test.ts must agree too"
    );
}
