//! Quentin's direction: pins that the server's and the client's
//! independent parsers agree on every field, mechanically. This is the
//! Rust side -- reads `sim::generated::defs`'s own compiled tables (what
//! the module actually consumes, no parsing involved) and checks a
//! canonical dump, in the exact same format the client's own
//! `tests/unit/defs/dump-golden.test.ts` independently produces
//! from the JSON side, against the one committed
//! `fixtures/defs-dump.v1.golden`. Never regenerated by this test; a
//! mismatch is exactly the moment a human must look.

use sim::generated::defs;

const GOLDEN: &str = include_str!("../../../fixtures/defs-dump.v1.golden");

fn family_str(family: defs::Family) -> &'static str {
    match family {
        defs::Family::Adult => "adult",
        defs::Family::Kid => "kid",
    }
}

fn pool_str(pool: defs::Pool) -> &'static str {
    match pool {
        defs::Pool::Civilian => "civilian",
        defs::Pool::RoleOnly => "role_only",
        defs::Pool::Costume => "costume",
    }
}

fn slot_str(slot: defs::Slot) -> &'static str {
    match slot {
        defs::Slot::Face => "face",
        defs::Slot::Head => "head",
        defs::Slot::Back => "back",
        defs::Slot::Torso => "torso",
        defs::Slot::Hands => "hands",
    }
}

fn canonical_dump() -> String {
    let mut lines: Vec<String> = Vec::new();

    for o in defs::OBJECTS {
        let rect = |r: Option<defs::ColliderRect>| match r {
            None => "none".to_string(),
            Some(c) => format!("{},{},{},{}", c.x0, c.y0, c.x1, c.y1),
        };
        let collider = rect(o.collider);
        let interact_at = rect(o.interact_at);
        lines.push(format!(
            "object {} id={} height={} width={} collider={collider} interact_at={interact_at} window={}",
            o.key, o.id, o.height, o.width, o.window
        ));
    }
    for i in defs::ITEMS {
        lines.push(format!("item {} id={}", i.key, i.id));
    }
    for r in defs::RECIPES {
        let mut inputs: Vec<&str> = r.inputs.to_vec();
        inputs.sort_unstable();
        let mut outputs: Vec<&str> = r.outputs.to_vec();
        outputs.sort_unstable();
        lines.push(format!(
            "recipe {} id={} inputs=[{}] outputs=[{}]",
            r.key,
            r.id,
            inputs.join(","),
            outputs.join(",")
        ));
    }
    for p in defs::PROFESSIONS {
        lines.push(format!("profession {} id={}", p.key, p.id));
    }
    for c in defs::CHAINS {
        let mut links: Vec<&str> = c.links.to_vec();
        links.sort_unstable();
        lines.push(format!(
            "chain {} id={} links=[{}]",
            c.key,
            c.id,
            links.join(",")
        ));
    }
    for b in defs::BALANCE {
        lines.push(format!(
            "balance {} value={} min={} max={}",
            b.key, b.value, b.min, b.max
        ));
    }
    for b in defs::BODIES {
        lines.push(format!(
            "body {} id={} family={} sheet={}",
            b.key,
            b.id,
            family_str(b.family),
            b.sheet
        ));
    }
    for e in defs::EYES {
        lines.push(format!(
            "eyes {} id={} family={} sheet={}",
            e.key,
            e.id,
            family_str(e.family),
            e.sheet
        ));
    }
    for h in defs::HAIRSTYLES {
        lines.push(format!(
            "hairstyle {} id={} family={} sheet={} style={} color={} rare={}",
            h.key,
            h.id,
            family_str(h.family),
            h.sheet,
            h.style,
            h.color,
            h.rare
        ));
    }
    for o in defs::OUTFITS {
        lines.push(format!(
            "outfit {} id={} family={} sheet={} pool={} hides_hairstyle={}",
            o.key,
            o.id,
            family_str(o.family),
            o.sheet,
            pool_str(o.pool),
            o.hides_hairstyle
        ));
    }
    for a in defs::ACCESSORIES {
        lines.push(format!(
            "accessory {} id={} family={} sheet={} pool={} slot={}",
            a.key,
            a.id,
            family_str(a.family),
            a.sheet,
            pool_str(a.pool),
            slot_str(a.slot)
        ));
    }
    for l in defs::APPEARANCE_LAYOUTS {
        let directions = l.directions.join(",");
        let rows: Vec<String> = l
            .rows
            .iter()
            .map(|r| format!("{}:{}:{}", r.animation, r.row, r.frames_per_direction))
            .collect();
        let accepted_sizes: Vec<String> = l
            .accepted_sizes
            .iter()
            .map(|(w, h)| format!("{w}x{h}"))
            .collect();
        lines.push(format!(
            "appearance_layout {} id={} family={} cell_width={} cell_height={} directions=[{}] rows=[{}] accepted_sizes=[{}]",
            l.key,
            l.id,
            family_str(l.family),
            l.cell_width,
            l.cell_height,
            directions,
            rows.join(","),
            accepted_sizes.join(",")
        ));
    }
    for u in defs::UNIFORMS {
        lines.push(format!(
            "uniform {} id={} profession={} outfit={} accessory={}",
            u.key,
            u.id,
            u.profession,
            u.outfit.unwrap_or("none"),
            u.accessory.unwrap_or("none")
        ));
    }

    lines.sort();
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

#[test]
fn matches_the_shared_golden_both_parsers_are_checked_against() {
    assert_eq!(
        canonical_dump(),
        GOLDEN,
        "sim::generated::defs's own canonical dump moved out of sync with fixtures/defs-dump.v1.golden -- if this is a deliberate defs/ change, the client's own tests/unit/defs/dump-golden.test.ts must agree too"
    );
}
