//! Story 1.4: restoring a logical export happens through owner-only
//! reducers, never through `spacetime sql` -- SpacetimeDB 2.9's SQL
//! `INSERT`/`UPDATE` cannot construct a `Timestamp` or `ScheduleAt`
//! literal at all (confirmed against the SQL reference and empirically;
//! see `docs/spikes/1.4-backup-restore.md`), so any table with one of
//! those columns cannot receive a row via SQL, full stop. A reducer has
//! no such limit: `#[spacetimedb::table]` structs derive `SpacetimeType`,
//! so a reducer can take `Vec<Row>` directly and `spacetime call` accepts
//! every SATS type as a JSON argument, Timestamp included.
//!
//! One `restore_<table>` reducer per non-scheduled table (never a
//! scheduled one -- schedules are derived state, `tables::schedules`),
//! each its own explicit `#[spacetimedb::reducer] pub fn` (never
//! generated by a `macro_rules!` invocation over the reducer name itself)
//! so `bounds::schema::reducer_names_in_dir`'s plain-text scan -- already
//! load-bearing for `schema_shape.rs`'s scheduled-reducer check -- finds
//! every one of them; `bounds/tests/restore_coverage.rs` is what makes
//! that mechanical rather than a claim in a doc comment. Gated the same
//! way as any other operator reducer (`tables::ops::require_owner`) and
//! by [`RestoreState`]: `begin_restore` refuses unless every
//! non-`init`-seeded table is already empty (the guard against restoring
//! over a live world), `restore_*` refuses unless a restore is open, and
//! `finish_restore` closes it permanently. `scripts/ops/restore-world.sh`
//! never enforces these rules itself -- it only calls the reducers in
//! order and reports what they say.
//!
//! **auto_inc tables never take an explicit id.** SpacetimeDB's auto_inc
//! sequence is a counter independent of a table's row content (confirmed
//! empirically: inserting an explicit high id does not advance it), so a
//! restored row is inserted with its id field set to `0` (the
//! auto-generate sentinel) like any other insert, and the generated id is
//! asserted to equal the exported one, via [`restore_autoinc_rows`]. When
//! it does not yet (the sequence is behind), the generated row is deleted
//! and another `0`-insert tried -- consuming exactly the ids between the
//! sequence's current position and the target, so the sequence ends
//! exactly where the export's did, not merely "not colliding today". If
//! a generated id ever overshoots the target (the target id was itself
//! skipped, e.g. exported ids that are not increasing) the reducer
//! aborts and the whole restore fails loudly rather than silently
//! reordering data.
//!
//! `restore_module_owner` and the five code-table restore reducers
//! delete their existing (`init`-seeded) rows first, then insert the
//! exported ones -- restore *replaces* what `init` seeded, the same rule
//! `scripts/ops/restore-world.sh` documented before this story moved the
//! write path into the module.

use spacetimedb::{ReducerContext, Table};

use crate::{DemoPing, demo_ping};

use super::citizen::{Citizen, CitizenState, citizen, citizen_state};
use super::codes::{
    MatterKind, NodeKind, Provision, ReasonCode, matter_kind, node_kind, provision, reason_code,
};
use super::identity::{Character, CharacterIdentity, character, character_identity};
use super::ops::{ModuleOwner, module_owner, require_owner};
use super::world::{
    Building, BuildingArea, FloorTransition, LayerCode, PlacedObject, Room, RoomArea, building,
    building_area, floor_transition, layer_code, placed_object, room, room_area,
};

/// Whether a restore is currently open -- a private, one-row gate no
/// reducer other than the three in this file ever reads or writes.
#[spacetimedb::table(accessor = restore_state)]
pub struct RestoreState {
    #[primary_key]
    id: u8,
    open: bool,
}

fn require_restore_open(ctx: &ReducerContext) -> Result<(), String> {
    match ctx.db.restore_state().id().find(0) {
        Some(row) if row.open => Ok(()),
        _ => Err("no restore is open -- call begin_restore first".to_string()),
    }
}

/// `init` seeds these (`module_owner`, the five code tables) -- restore
/// *replaces* their content rather than requiring them empty. The single
/// source of truth for which tables that is: `bounds/tests/
/// restore_coverage.rs`'s text scan reads this constant's own source
/// (never a second, hand-copied list) and fails CI if a non-scheduled
/// table is in neither this list nor [`NON_INIT_SEEDED_TABLES`].
#[allow(dead_code)] // read by `restore_coverage.rs` as source text, not Rust code
const INIT_SEEDED_TABLES: &[&str] = &[
    "module_owner",
    "matter_kind",
    "provision",
    "reason_code",
    "node_kind",
    "layer_code",
];

/// Every non-scheduled table `init` does *not* seed -- `begin_restore`
/// refuses unless every one of these is empty. The single source of
/// truth: `bounds/tests/restore_coverage.rs`'s text scan reads this
/// constant's own source and fails CI if a table here has no matching
/// `ctx.db.<accessor>().iter().next().is_some()` check in
/// `begin_restore`'s body below, or if a non-scheduled table is in
/// neither this list nor [`INIT_SEEDED_TABLES`] -- so a table added next
/// month without an entry here is a build failure, not a silent hole in
/// "never restore over a live world".
#[allow(dead_code)] // read by `restore_coverage.rs` as source text, not Rust code
const NON_INIT_SEEDED_TABLES: &[&str] = &[
    "demo_ping",
    "building",
    "building_area",
    "character",
    "character_identity",
    "citizen",
    "citizen_state",
    "floor_transition",
    "placed_object",
    "room",
    "room_area",
];

/// Opens a restore. Refuses unless every table in
/// [`NON_INIT_SEEDED_TABLES`] is empty -- the guard against restoring
/// over a live world. Idempotent-refusing: calling it again while a
/// restore is already open is an error, not a silent no-op, so a
/// half-finished restore is never quietly resumed with a different
/// export.
#[spacetimedb::reducer]
pub fn begin_restore(ctx: &ReducerContext) -> Result<(), String> {
    require_owner(ctx)?;
    if let Some(row) = ctx.db.restore_state().id().find(0)
        && row.open
    {
        return Err("a restore is already open -- call finish_restore first".to_string());
    }
    let mut nonempty: Vec<&str> = Vec::new();
    if ctx.db.demo_ping().iter().next().is_some() {
        nonempty.push("demo_ping");
    }
    if ctx.db.building().iter().next().is_some() {
        nonempty.push("building");
    }
    if ctx.db.building_area().iter().next().is_some() {
        nonempty.push("building_area");
    }
    if ctx.db.character().iter().next().is_some() {
        nonempty.push("character");
    }
    if ctx.db.character_identity().iter().next().is_some() {
        nonempty.push("character_identity");
    }
    if ctx.db.citizen().iter().next().is_some() {
        nonempty.push("citizen");
    }
    if ctx.db.citizen_state().iter().next().is_some() {
        nonempty.push("citizen_state");
    }
    if ctx.db.floor_transition().iter().next().is_some() {
        nonempty.push("floor_transition");
    }
    if ctx.db.placed_object().iter().next().is_some() {
        nonempty.push("placed_object");
    }
    if ctx.db.room().iter().next().is_some() {
        nonempty.push("room");
    }
    if ctx.db.room_area().iter().next().is_some() {
        nonempty.push("room_area");
    }
    if !nonempty.is_empty() {
        return Err(format!(
            "begin_restore refuses a target that is not freshly published -- already has row(s) in: {}",
            nonempty.join(", ")
        ));
    }

    match ctx.db.restore_state().id().find(0) {
        Some(_) => {
            ctx.db
                .restore_state()
                .id()
                .update(RestoreState { id: 0, open: true });
        }
        None => {
            ctx.db
                .restore_state()
                .insert(RestoreState { id: 0, open: true });
        }
    }
    Ok(())
}

/// Closes a restore permanently. Never reopened by calling this again --
/// a second `begin_restore` after `finish_restore` opens a *new* restore
/// (and re-checks every precondition), it does not resume this one.
#[spacetimedb::reducer]
pub fn finish_restore(ctx: &ReducerContext) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    ctx.db
        .restore_state()
        .id()
        .update(RestoreState { id: 0, open: false });
    Ok(())
}

/// An auto_inc table's row, reduced to what [`restore_autoinc_rows`]
/// needs: its own id, and a copy of itself with a different one. One
/// tiny impl per auto_inc table (below) -- never a derive, since the id
/// field's name differs per table.
trait AutoIncRow: Clone {
    fn id(&self) -> u64;
    fn with_id(&self, id: u64) -> Self;
}

/// The shared gap-filling loop this file's module doc describes, generic
/// over one auto_inc table's row type. `insert`/`delete` close over
/// `ctx` and the one table this call restores -- kept as closures rather
/// than a `ctx`/accessor parameter because there is no shared trait
/// across SpacetimeDB's per-table generated accessor types to abstract
/// that part genuinely generically.
fn restore_autoinc_rows<T: AutoIncRow>(
    rows: Vec<T>,
    mut insert: impl FnMut(T) -> T,
    mut delete: impl FnMut(u64),
    table_name: &str,
) -> Result<(), String> {
    for row in rows {
        let target_id = row.id();
        loop {
            let inserted = insert(row.with_id(0));
            let got = inserted.id();
            if got == target_id {
                break;
            } else if got < target_id {
                delete(got);
            } else {
                delete(got);
                return Err(format!(
                    "'{table_name}': the generated id {got} overshot the exported id {target_id} -- exported ids must be strictly increasing and gap-free from the sequence's own position; restore aborted"
                ));
            }
        }
    }
    Ok(())
}

macro_rules! impl_autoinc_row {
    ($Row:ty, $id_field:ident) => {
        impl AutoIncRow for $Row {
            fn id(&self) -> u64 {
                self.$id_field
            }
            fn with_id(&self, id: u64) -> Self {
                let mut copy = self.clone();
                copy.$id_field = id;
                copy
            }
        }
    };
}

impl_autoinc_row!(DemoPing, id);
impl_autoinc_row!(Building, building_id);
impl_autoinc_row!(BuildingArea, area_id);
impl_autoinc_row!(Character, character_id);
impl_autoinc_row!(CharacterIdentity, mapping_id);
impl_autoinc_row!(Citizen, citizen_id);
impl_autoinc_row!(FloorTransition, transition_id);
impl_autoinc_row!(PlacedObject, object_id);
impl_autoinc_row!(Room, room_id);
impl_autoinc_row!(RoomArea, area_id);

#[spacetimedb::reducer]
pub fn restore_demo_ping(ctx: &ReducerContext, rows: Vec<DemoPing>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.demo_ping().insert(r),
        |id| {
            ctx.db.demo_ping().id().delete(id);
        },
        "demo_ping",
    )
}

#[spacetimedb::reducer]
pub fn restore_building(ctx: &ReducerContext, rows: Vec<Building>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.building().insert(r),
        |id| {
            ctx.db.building().building_id().delete(id);
        },
        "building",
    )
}

#[spacetimedb::reducer]
pub fn restore_building_area(ctx: &ReducerContext, rows: Vec<BuildingArea>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.building_area().insert(r),
        |id| {
            ctx.db.building_area().area_id().delete(id);
        },
        "building_area",
    )
}

#[spacetimedb::reducer]
pub fn restore_character(ctx: &ReducerContext, rows: Vec<Character>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.character().insert(r),
        |id| {
            ctx.db.character().character_id().delete(id);
        },
        "character",
    )
}

#[spacetimedb::reducer]
pub fn restore_character_identity(
    ctx: &ReducerContext,
    rows: Vec<CharacterIdentity>,
) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.character_identity().insert(r),
        |id| {
            ctx.db.character_identity().mapping_id().delete(id);
        },
        "character_identity",
    )
}

#[spacetimedb::reducer]
pub fn restore_citizen(ctx: &ReducerContext, rows: Vec<Citizen>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.citizen().insert(r),
        |id| {
            ctx.db.citizen().citizen_id().delete(id);
        },
        "citizen",
    )
}

#[spacetimedb::reducer]
pub fn restore_floor_transition(
    ctx: &ReducerContext,
    rows: Vec<FloorTransition>,
) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.floor_transition().insert(r),
        |id| {
            ctx.db.floor_transition().transition_id().delete(id);
        },
        "floor_transition",
    )
}

#[spacetimedb::reducer]
pub fn restore_placed_object(ctx: &ReducerContext, rows: Vec<PlacedObject>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.placed_object().insert(r),
        |id| {
            ctx.db.placed_object().object_id().delete(id);
        },
        "placed_object",
    )
}

#[spacetimedb::reducer]
pub fn restore_room(ctx: &ReducerContext, rows: Vec<Room>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.room().insert(r),
        |id| {
            ctx.db.room().room_id().delete(id);
        },
        "room",
    )
}

#[spacetimedb::reducer]
pub fn restore_room_area(ctx: &ReducerContext, rows: Vec<RoomArea>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.room_area().insert(r),
        |id| {
            ctx.db.room_area().area_id().delete(id);
        },
        "room_area",
    )
}

// --- direct insert: not auto_inc, not init-seeded, so `begin_restore`
// already guaranteed the table is empty -------------------------------
#[spacetimedb::reducer]
pub fn restore_citizen_state(ctx: &ReducerContext, rows: Vec<CitizenState>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    for row in rows {
        ctx.db.citizen_state().insert(row);
    }
    Ok(())
}

// --- replace: init-seeded (module_owner, the code tables) -- restore
// deletes what init seeded, then inserts the exported rows ------------
#[spacetimedb::reducer]
pub fn restore_module_owner(ctx: &ReducerContext, rows: Vec<ModuleOwner>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    // The module's own guard against locking the operator out, not only
    // restore-world.sh's early, friendlier message (Tim's direction):
    // an empty or foreign `module_owner.jsonl` must never be allowed to
    // delete the only owner this reducer is about to remove.
    match rows.as_slice() {
        [row] if row.owner == ctx.sender() => {}
        [row] => {
            return Err(format!(
                "restore_module_owner refuses to restore an owner ({}) that is not the caller ({}) -- require_owner would lock the operator out of the restored world",
                row.owner,
                ctx.sender()
            ));
        }
        other => {
            return Err(format!(
                "restore_module_owner requires exactly one row, got {}",
                other.len()
            ));
        }
    }
    let existing: Vec<u8> = ctx.db.module_owner().iter().map(|r| r.id).collect();
    for id in existing {
        ctx.db.module_owner().id().delete(id);
    }
    for row in rows {
        ctx.db.module_owner().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_matter_kind(ctx: &ReducerContext, rows: Vec<MatterKind>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.matter_kind().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.matter_kind().code().delete(code);
    }
    for row in rows {
        ctx.db.matter_kind().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_provision(ctx: &ReducerContext, rows: Vec<Provision>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.provision().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.provision().code().delete(code);
    }
    for row in rows {
        ctx.db.provision().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_reason_code(ctx: &ReducerContext, rows: Vec<ReasonCode>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.reason_code().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.reason_code().code().delete(code);
    }
    for row in rows {
        ctx.db.reason_code().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_node_kind(ctx: &ReducerContext, rows: Vec<NodeKind>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.node_kind().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.node_kind().code().delete(code);
    }
    for row in rows {
        ctx.db.node_kind().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_layer_code(ctx: &ReducerContext, rows: Vec<LayerCode>) -> Result<(), String> {
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.layer_code().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.layer_code().code().delete(code);
    }
    for row in rows {
        ctx.db.layer_code().insert(row);
    }
    Ok(())
}
