//! Story 1.4: restoring a logical export happens through owner-only
//! reducers, never through `spacetime sql` -- SpacetimeDB 2.9's SQL
//! `INSERT`/`UPDATE` cannot construct a `Timestamp` or `ScheduleAt`
//! literal at all (confirmed against the SQL reference and empirically;
//! see `docs/spikes/1.4-backup-restore.md`), so any table with one of
//! those columns cannot receive a row via SQL, full stop. A reducer has
//! no such limit: `#[spacetimedb::table]` structs derive `SpacetimeType`,
//! so a reducer can take `Vec<Row>` directly and `spacetime call` accepts
//! every SATS type as a JSON argument, Timestamp included.
//!
//! One `restore_<table>` reducer per non-scheduled table (never a
//! scheduled one -- schedules are derived state, `tables::schedules`),
//! each its own explicit `#[spacetimedb::reducer] pub fn` (never
//! generated by a `macro_rules!` invocation over the reducer name itself)
//! so `bounds::schema::reducer_names_in_dir`'s plain-text scan -- already
//! load-bearing for `schema_shape.rs`'s scheduled-reducer check -- finds
//! every one of them; `bounds/tests/restore_coverage.rs` is what makes
//! that mechanical rather than a claim in a doc comment. Gated the same
//! way as any other operator reducer (`tables::ops::require_owner`) and
//! by [`RestoreState`]: `begin_restore` refuses unless every
//! non-`init`-seeded table is already empty (the guard against restoring
//! over a live world), `restore_*` refuses unless a restore is open, and
//! `finish_restore` closes it permanently. `scripts/ops/restore-world.sh`
//! never enforces these rules itself -- it only calls the reducers in
//! order and reports what they say.
//!
//! **auto_inc tables never take an explicit id.** SpacetimeDB's auto_inc
//! sequence is a counter independent of a table's row content (confirmed
//! empirically: inserting an explicit high id does not advance it), so a
//! restored row is inserted with its id field set to `0` (the
//! auto-generate sentinel) like any other insert, and the generated id is
//! asserted to equal the exported one, via [`restore_autoinc_rows`]. When
//! it does not yet (the sequence is behind), the generated row is deleted
//! and another `0`-insert tried -- consuming exactly the ids between the
//! sequence's current position and the target. If a generated id ever
//! overshoots the target (the target id was itself skipped, e.g.
//! exported ids that are not increasing) the reducer aborts and the whole
//! restore fails loudly rather than silently reordering data.
//!
//! **The sequence never re-issues an id the source ever handed out, not
//! merely the highest one still present in the export.** Restoring only
//! up to the restored data's own maximum id would let the *next*
//! player-created row reuse an id the source deleted off a table's tail
//! before export -- and since export is consistent per table, not across
//! tables, a dangling reference in another table (a `character_identity`
//! row pointing at a `character_id` already gone) could then resolve to
//! whatever *new* row lands on that reused id. Every `restore_<table>`
//! reducer therefore also takes `sequence_floor: u64`
//! (`scripts/ops/export-world.sh` records it per table in
//! `manifest.json`, read from `st_sequence.allocated` at export time --
//! a safe upper bound, since nothing above it was ever issued, and a
//! hard, immediate error if that record is missing: there is no legacy
//! export to fall back to `0`, "do not advance", for) and, after placing
//! every exported row, advances the sequence to at least that floor --
//! never by inserting a fresh, made-up row and leaving it there.
//! [`AutoIncRow::placeholder`] (one const literal per table,
//! `impl_autoinc_row!`'s own third argument, never `Default`: a
//! `Default` impl on the row type itself would be a public, meaningless
//! constructor gameplay code could also reach) exists only for a table
//! with no exported rows at all to reuse instead; the far more common
//! case reuses the *last exported row placed* -- deleted, then
//! re-inserted with its own real id once the advance is done -- so a
//! `#[unique]` column (`character_identity.identity`, today) can never
//! collide with a made-up throwaway value while a real row's own values
//! are already sitting in the table. Multi-batch restores must pass `0`
//! (a permanent no-op) for every batch but a table's own last one --
//! advancing early would place the sequence past a still-to-come batch's
//! own target ids, which the gap-fill loop above would then read as an
//! overshoot and abort on.
//!
//! `restore_module_owner` and the seven code-table restore reducers
//! delete their existing (`init`-seeded) rows first, then insert the
//! exported ones -- restore *replaces* what `init` seeded, the same rule
//! `scripts/ops/restore-world.sh` documented before this story moved the
//! write path into the module. `restore_cadence_liveness` (story 4.2)
//! does the same, for the same reason under a different cause: `init`
//! never seeds it directly, but the cadence it arms can fire and write it
//! before `begin_restore` ever runs.
//!
//! `begin_restore` also disarms every scheduled table
//! (`tables::schedules::disarm_all_scheduled_tables`) before its own
//! emptiness checks, and `finish_restore` re-arms every cadence
//! (`tables::schedules::arm_every_cadence`) after closing the restore --
//! both inside this file, so no cadence can ever fire between the two
//! using an epoch that does not belong to the world being restored
//! (story 4.2). `scripts/ops/restore-world.sh` calls neither directly.

use spacetimedb::{Identity, ReducerContext, Table, Timestamp};

use crate::{DemoPing, demo_ping};

use super::citizen::{Citizen, CitizenState, citizen, citizen_state};
use super::clock::{WorldClock, world_clock};
use super::codes::{
    ContainerKind, HolderKind, MatterKind, NodeKind, Provision, ReasonCode, Unit, container_kind,
    holder_kind, matter_kind, node_kind, provision, reason_code, unit,
};
use super::district::{District, district};
use super::identity::{
    Character, CharacterIdentity, LinkRequest, OidcIssuer, character, character_identity,
    link_request, oidc_issuer,
};
use super::item_instance::{
    ItemHeld, ItemInstance, ItemPlaced, item_held, item_instance, item_placed,
};
use super::metrics::{
    ReducerClassCounter, ReducerClassSample, StorageSample, TableSample, count_call,
    reducer_class_counter, reducer_class_sample, storage_sample, table_sample,
};
use super::ops::{ModuleOwner, module_owner, require_owner};
use super::schedules::{CadenceLiveness, cadence_liveness};
use super::stock::{Business, Stock, business, stock};
use super::world::{
    Building, BuildingArea, FloorTransition, LayerCode, PlacedObject, Room, RoomArea, building,
    building_area, floor_transition, layer_code, placed_object, room, room_area,
};
use sim::reducer_classes::ReducerClass;

/// Whether a restore is currently open -- a private, one-row gate no
/// reducer other than the three in this file ever reads or writes.
#[spacetimedb::table(accessor = restore_state)]
pub struct RestoreState {
    #[primary_key]
    id: u8,
    open: bool,
}

fn require_restore_open(ctx: &ReducerContext) -> Result<(), String> {
    match ctx.db.restore_state().id().find(0) {
        Some(row) if row.open => Ok(()),
        _ => Err("no restore is open -- call begin_restore first".to_string()),
    }
}

/// A table restore *replaces* rather than requires empty: `init` seeds
/// `module_owner` and the six code tables directly; `cadence_liveness`
/// is different in cause but the same in consequence -- a freshly
/// published target's own `init` arms its cadence immediately
/// (`tables::schedules::arm_every_cadence_from`), and that cadence can
/// fire for real, writing this table, at any point before `begin_restore`
/// ever runs, so requiring it empty would refuse an otherwise-valid
/// restore purely on timing. The single source of truth for which tables
/// this is: `bounds/tests/restore_coverage.rs`'s text scan reads this
/// constant's own source (never a second, hand-copied list) and fails CI
/// if a non-scheduled table is in neither this list nor
/// [`NON_INIT_SEEDED_TABLES`].
#[allow(dead_code)] // read by `restore_coverage.rs` as source text, not Rust code
const INIT_SEEDED_TABLES: &[&str] = &[
    "module_owner",
    "world_clock",
    "matter_kind",
    "provision",
    "reason_code",
    "node_kind",
    "unit",
    "holder_kind",
    "container_kind",
    "layer_code",
    "cadence_liveness",
    "storage_sample",
    "table_sample",
    "reducer_class_counter",
    "reducer_class_sample",
];

/// Every non-scheduled table that is never pre-populated before
/// `begin_restore` -- `begin_restore` refuses unless every one of these
/// is empty. The single source of truth: `bounds/tests/
/// restore_coverage.rs`'s text scan reads this constant's own source and
/// fails CI if a table here has no matching
/// `ctx.db.<accessor>().iter().next().is_some()` check in
/// `begin_restore`'s body below, or if a non-scheduled table is in
/// neither this list nor [`INIT_SEEDED_TABLES`] -- so a table added next
/// month without an entry here is a build failure, not a silent hole in
/// "never restore over a live world".
#[allow(dead_code)] // read by `restore_coverage.rs` as source text, not Rust code
const NON_INIT_SEEDED_TABLES: &[&str] = &[
    "item_instance",
    "item_placed",
    "item_held",
    "business",
    "stock",
    "demo_ping",
    "building",
    "building_area",
    "district",
    "character",
    "character_identity",
    "oidc_issuer",
    "link_request",
    "citizen",
    "citizen_state",
    "floor_transition",
    "placed_object",
    "room",
    "room_area",
];

/// Opens a restore. Disarms every scheduled table first
/// (`tables::schedules::disarm_all_scheduled_tables`) -- a freshly
/// published target's own `init` arms its cadence immediately, so without
/// this a scheduled reducer could fire on the target at any point during
/// the restore, using an epoch that belongs to the target's own
/// pre-restore world, not the one being restored (story 4.2). Then
/// refuses unless every table in [`NON_INIT_SEEDED_TABLES`] is empty --
/// the guard against restoring over a live world. Idempotent-refusing:
/// calling it again while a restore is already open is an error, not a
/// silent no-op, so a half-finished restore is never quietly resumed
/// with a different export.
#[spacetimedb::reducer]
pub fn begin_restore(ctx: &ReducerContext) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    if let Some(row) = ctx.db.restore_state().id().find(0)
        && row.open
    {
        return Err("a restore is already open -- call finish_restore first".to_string());
    }
    super::schedules::disarm_all_scheduled_tables(ctx);
    // The metrics samples are ops data measured from the target's own
    // pre-restore state, worthless by definition, and the sampler may have
    // fired on a target published more than an hour ago: cleared here
    // (after the disarm, so no fire lands in between) rather than required
    // empty, the same stance `restore_cadence_liveness` takes. The
    // `restore_*` reducers then restore into the empty tables.
    for id in ctx
        .db
        .table_sample()
        .iter()
        .map(|r| r.sample_id)
        .collect::<Vec<_>>()
    {
        ctx.db.table_sample().sample_id().delete(id);
    }
    for id in ctx
        .db
        .storage_sample()
        .iter()
        .map(|r| r.sample_id)
        .collect::<Vec<_>>()
    {
        ctx.db.storage_sample().sample_id().delete(id);
    }
    for id in ctx
        .db
        .reducer_class_sample()
        .iter()
        .map(|r| r.sample_id)
        .collect::<Vec<_>>()
    {
        ctx.db.reducer_class_sample().sample_id().delete(id);
    }
    let mut nonempty: Vec<&str> = Vec::new();
    if ctx.db.demo_ping().iter().next().is_some() {
        nonempty.push("demo_ping");
    }
    if ctx.db.business().iter().next().is_some() {
        nonempty.push("business");
    }
    if ctx.db.item_instance().iter().next().is_some() {
        nonempty.push("item_instance");
    }
    if ctx.db.item_placed().iter().next().is_some() {
        nonempty.push("item_placed");
    }
    if ctx.db.item_held().iter().next().is_some() {
        nonempty.push("item_held");
    }
    if ctx.db.stock().iter().next().is_some() {
        nonempty.push("stock");
    }
    if ctx.db.building().iter().next().is_some() {
        nonempty.push("building");
    }
    if ctx.db.building_area().iter().next().is_some() {
        nonempty.push("building_area");
    }
    if ctx.db.district().iter().next().is_some() {
        nonempty.push("district");
    }
    if ctx.db.character().iter().next().is_some() {
        nonempty.push("character");
    }
    if ctx.db.character_identity().iter().next().is_some() {
        nonempty.push("character_identity");
    }
    if ctx.db.oidc_issuer().iter().next().is_some() {
        nonempty.push("oidc_issuer");
    }
    if ctx.db.link_request().iter().next().is_some() {
        nonempty.push("link_request");
    }
    if ctx.db.citizen().iter().next().is_some() {
        nonempty.push("citizen");
    }
    if ctx.db.citizen_state().iter().next().is_some() {
        nonempty.push("citizen_state");
    }
    if ctx.db.floor_transition().iter().next().is_some() {
        nonempty.push("floor_transition");
    }
    if ctx.db.placed_object().iter().next().is_some() {
        nonempty.push("placed_object");
    }
    if ctx.db.room().iter().next().is_some() {
        nonempty.push("room");
    }
    if ctx.db.room_area().iter().next().is_some() {
        nonempty.push("room_area");
    }
    if !nonempty.is_empty() {
        return Err(format!(
            "begin_restore refuses a target that is not freshly published -- already has row(s) in: {}",
            nonempty.join(", ")
        ));
    }

    match ctx.db.restore_state().id().find(0) {
        Some(_) => {
            ctx.db
                .restore_state()
                .id()
                .update(RestoreState { id: 0, open: true });
        }
        None => {
            ctx.db
                .restore_state()
                .insert(RestoreState { id: 0, open: true });
        }
    }
    Ok(())
}

/// Closes a restore permanently. Never reopened by calling this again --
/// a second `begin_restore` after `finish_restore` opens a *new* restore
/// (and re-checks every precondition), it does not resume this one. Then
/// re-arms every cadence from the epoch `restore_world_clock` just
/// restored (`tables::schedules::arm_every_cadence`) -- inside this same
/// transaction chain, so a restored world resumes its loop with no window
/// in which any cadence is armed from anything but the epoch actually
/// being restored (story 4.2).
#[spacetimedb::reducer]
pub fn finish_restore(ctx: &ReducerContext) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    ctx.db
        .restore_state()
        .id()
        .update(RestoreState { id: 0, open: false });
    super::schedules::arm_every_cadence(ctx)
}

/// An auto_inc table's row, reduced to what [`restore_autoinc_rows`]
/// needs: its own id, a copy of itself with a different one, and (only
/// for the case a table has no exported rows at all to reuse, below) one
/// throwaway placeholder value, supplied per table
/// (`impl_autoinc_row!`'s own third argument), never derived. Never
/// `Default` on the row type itself (Tim's direction): that would be a
/// public, meaningless constructor (`Character::default()`, for one)
/// gameplay code could also reach -- restore concerns must not leak into
/// domain types.
trait AutoIncRow: Clone {
    fn id(&self) -> u64;
    fn with_id(&self, id: u64) -> Self;
    fn placeholder() -> Self;
}

/// The shared gap-filling loop this file's module doc describes, generic
/// over one auto_inc table's row type. `insert`/`delete` close over
/// `ctx` and the one table this call restores -- kept as closures rather
/// than a `ctx`/accessor parameter because there is no shared trait
/// across SpacetimeDB's per-table generated accessor types to abstract
/// that part genuinely generically.
///
/// `sequence_floor`, after every row is placed, advances the sequence to
/// at least that position -- never merely to the highest *exported* id.
/// Restoring only up to the restored data's own maximum id can re-issue
/// an id the source already handed out and later deleted (a dangling
/// `character_identity.identity` pointing at a `character_id` no longer
/// present, for one): the next player-created row on the restored
/// database would then collide with that stale reference instead of a
/// fresh id. `sequence_floor` is `st_sequence.allocated` at export time
/// (`scripts/ops/export-world.sh`, `manifest.json`'s own
/// `sequence_floors`) -- a safe upper bound, since nothing above it was
/// ever issued. **Pass `0` for every call but a table's own last batch**
/// -- advancing early would place the sequence past a still-to-come
/// batch's own target ids, which the loop above would then read as an
/// overshoot and abort on.
///
/// The throwaway rows this advance inserts-then-deletes to consume ids
/// must never collide with a real one on a `#[unique]` column
/// (`character_identity.identity`, today): if at least one row was
/// placed, the *last* one placed (`R`) is deleted, cloned with id `0`
/// repeatedly until the generated id reaches the floor, and then
/// re-inserted with its own real, explicit id -- safe, because the
/// sequence is already past it, and `R`'s own unique values cannot
/// collide with the throwaway clones carrying the exact same values,
/// deleted again before the next one is ever inserted. If no row was
/// placed at all (a table with a nonzero floor but nothing exported --
/// rows once existed and were deleted before export), an explicit
/// per-table `placeholder()` is used instead: an empty table has nothing
/// to collide with.
fn restore_autoinc_rows<T: AutoIncRow>(
    rows: Vec<T>,
    mut insert: impl FnMut(T) -> T,
    mut delete: impl FnMut(u64),
    table_name: &str,
    sequence_floor: u64,
) -> Result<(), String> {
    let mut last_placed: Option<T> = None;
    for row in rows {
        let target_id = row.id();
        loop {
            let inserted = insert(row.with_id(0));
            let got = inserted.id();
            if got == target_id {
                last_placed = Some(inserted);
                break;
            } else if got < target_id {
                delete(got);
            } else {
                delete(got);
                return Err(format!(
                    "'{table_name}': the generated id {got} overshot the exported id {target_id} -- exported ids must be strictly increasing and gap-free from the sequence's own position; restore aborted"
                ));
            }
        }
    }
    if sequence_floor > 0 {
        match last_placed {
            Some(r) => {
                delete(r.id());
                loop {
                    let inserted = insert(r.with_id(0));
                    let got = inserted.id();
                    delete(got);
                    if got >= sequence_floor {
                        break;
                    }
                }
                insert(r);
            }
            None => loop {
                let inserted = insert(T::placeholder().with_id(0));
                let got = inserted.id();
                delete(got);
                if got >= sequence_floor {
                    break;
                }
            },
        }
    }
    Ok(())
}

/// `$placeholder` is an explicit literal, never `Default::default()`: a
/// table's own `placeholder()` is only ever reached when that table has
/// no exported rows to reuse instead (`restore_autoinc_rows`'s own doc
/// comment above) -- field values otherwise never matter, since the row
/// is deleted again immediately and nothing else exists yet to collide
/// with.
macro_rules! impl_autoinc_row {
    ($Row:ty, $id_field:ident, $placeholder:expr) => {
        impl AutoIncRow for $Row {
            fn id(&self) -> u64 {
                self.$id_field
            }
            fn with_id(&self, id: u64) -> Self {
                let mut copy = self.clone();
                copy.$id_field = id;
                copy
            }
            fn placeholder() -> Self {
                $placeholder
            }
        }
    };
}

impl_autoinc_row!(
    DemoPing,
    id,
    DemoPing {
        id: 0,
        message: String::new(),
        written_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    Building,
    building_id,
    Building {
        building_id: 0,
        created_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    BuildingArea,
    area_id,
    BuildingArea {
        area_id: 0,
        building_id: 0,
        x0: 0,
        y0: 0,
        x1: 0,
        y1: 0,
        floor: 0,
        chunk_key: 0,
    }
);
impl_autoinc_row!(
    District,
    district_id,
    District {
        district_id: 0,
        seed: 0,
        x0: 0,
        y0: 0,
        x1: 0,
        y1: 0,
        generation_version: 0,
        rng_version: 0,
        defs_version: String::new(),
        generated_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    Character,
    character_id,
    Character {
        character_id: 0,
        created_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    CharacterIdentity,
    mapping_id,
    CharacterIdentity {
        mapping_id: 0,
        identity: Identity::default(),
        character_id: 0,
        issuer_id: 0,
    }
);
impl_autoinc_row!(
    OidcIssuer,
    issuer_id,
    OidcIssuer {
        issuer_id: 0,
        issuer: String::new(),
        client_id: String::new(),
    }
);
impl_autoinc_row!(
    LinkRequest,
    request_id,
    LinkRequest {
        request_id: 0,
        identity: Identity::default(),
        issuer_id: 0,
        code: String::new(),
        expires_at: 0,
    }
);
impl_autoinc_row!(
    Citizen,
    citizen_id,
    Citizen {
        citizen_id: 0,
        created_at: Timestamp::UNIX_EPOCH,
        appearance_body: 0,
        appearance_eyes: 0,
        appearance_outfit: 0,
        appearance_hairstyle: 0,
        appearance_accessory: 0,
    }
);
impl_autoinc_row!(
    Business,
    business_id,
    Business {
        business_id: 0,
        created_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    ItemInstance,
    instance_id,
    ItemInstance {
        instance_id: 0,
        def_id: 0,
        created_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    Stock,
    stock_id,
    Stock {
        stock_id: 0,
        holder_kind: 0,
        holder_id: 0,
        item_id: 0,
        quantity: 0,
    }
);
impl_autoinc_row!(
    TableSample,
    sample_id,
    TableSample {
        sample_id: 0,
        sampled_at: Timestamp::UNIX_EPOCH,
        table_accessor: String::new(),
        rows: 0,
        bytes_est: 0,
        alert_rows: 0,
        max_rows: 0,
        over_alert: false,
    }
);
impl_autoinc_row!(
    StorageSample,
    sample_id,
    StorageSample {
        sample_id: 0,
        sampled_at: Timestamp::UNIX_EPOCH,
        total_bytes_est: 0,
        over_review: false,
        over_wall: false,
        review_bytes: 0,
        wall_bytes: 0,
    }
);
impl_autoinc_row!(
    ReducerClassSample,
    sample_id,
    ReducerClassSample {
        sample_id: 0,
        sampled_at: Timestamp::UNIX_EPOCH,
        class: String::new(),
        calls_total: 0,
        calls_delta: 0,
    }
);
impl_autoinc_row!(
    FloorTransition,
    transition_id,
    FloorTransition {
        transition_id: 0,
        x: 0,
        y: 0,
        floor: 0,
        target_x: 0,
        target_y: 0,
        target_floor: 0,
        chunk_key: 0,
    }
);
impl_autoinc_row!(
    PlacedObject,
    object_id,
    PlacedObject {
        object_id: 0,
        def_id: 0,
        x: 0,
        y: 0,
        floor: 0,
        layer: 0,
        orientation: 0,
        chunk_key: 0,
    }
);
impl_autoinc_row!(
    Room,
    room_id,
    Room {
        room_id: 0,
        building_id: 0,
        created_at: Timestamp::UNIX_EPOCH,
    }
);
impl_autoinc_row!(
    RoomArea,
    area_id,
    RoomArea {
        area_id: 0,
        room_id: 0,
        x0: 0,
        y0: 0,
        x1: 0,
        y1: 0,
        floor: 0,
        chunk_key: 0,
    }
);

#[spacetimedb::reducer]
pub fn restore_demo_ping(
    ctx: &ReducerContext,
    rows: Vec<DemoPing>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.demo_ping().insert(r),
        |id| {
            ctx.db.demo_ping().id().delete(id);
        },
        "demo_ping",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_building(
    ctx: &ReducerContext,
    rows: Vec<Building>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.building().insert(r),
        |id| {
            ctx.db.building().building_id().delete(id);
        },
        "building",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_building_area(
    ctx: &ReducerContext,
    rows: Vec<BuildingArea>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.building_area().insert(r),
        |id| {
            ctx.db.building_area().area_id().delete(id);
        },
        "building_area",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_district(
    ctx: &ReducerContext,
    rows: Vec<District>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.district().insert(r),
        |id| {
            ctx.db.district().district_id().delete(id);
        },
        "district",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_character(
    ctx: &ReducerContext,
    rows: Vec<Character>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.character().insert(r),
        |id| {
            ctx.db.character().character_id().delete(id);
        },
        "character",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_character_identity(
    ctx: &ReducerContext,
    rows: Vec<CharacterIdentity>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.character_identity().insert(r),
        |id| {
            ctx.db.character_identity().mapping_id().delete(id);
        },
        "character_identity",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_oidc_issuer(
    ctx: &ReducerContext,
    rows: Vec<OidcIssuer>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.oidc_issuer().insert(r),
        |id| {
            ctx.db.oidc_issuer().issuer_id().delete(id);
        },
        "oidc_issuer",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_link_request(
    ctx: &ReducerContext,
    rows: Vec<LinkRequest>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.link_request().insert(r),
        |id| {
            ctx.db.link_request().request_id().delete(id);
        },
        "link_request",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_citizen(
    ctx: &ReducerContext,
    rows: Vec<Citizen>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.citizen().insert(r),
        |id| {
            ctx.db.citizen().citizen_id().delete(id);
        },
        "citizen",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_business(
    ctx: &ReducerContext,
    rows: Vec<Business>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.business().insert(r),
        |id| {
            ctx.db.business().business_id().delete(id);
        },
        "business",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_item_instance(
    ctx: &ReducerContext,
    rows: Vec<ItemInstance>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.item_instance().insert(r),
        |id| {
            ctx.db.item_instance().instance_id().delete(id);
        },
        "item_instance",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_item_placed(ctx: &ReducerContext, rows: Vec<ItemPlaced>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    for row in rows {
        ctx.db.item_placed().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_item_held(ctx: &ReducerContext, rows: Vec<ItemHeld>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    for row in rows {
        ctx.db.item_held().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_container_kind(
    ctx: &ReducerContext,
    rows: Vec<ContainerKind>,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.container_kind().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.container_kind().code().delete(code);
    }
    for row in rows {
        ctx.db.container_kind().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_stock(
    ctx: &ReducerContext,
    rows: Vec<Stock>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.stock().insert(r),
        |id| {
            ctx.db.stock().stock_id().delete(id);
        },
        "stock",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_table_sample(
    ctx: &ReducerContext,
    rows: Vec<TableSample>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.table_sample().insert(r),
        |id| {
            ctx.db.table_sample().sample_id().delete(id);
        },
        "table_sample",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_storage_sample(
    ctx: &ReducerContext,
    rows: Vec<StorageSample>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.storage_sample().insert(r),
        |id| {
            ctx.db.storage_sample().sample_id().delete(id);
        },
        "storage_sample",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_reducer_class_sample(
    ctx: &ReducerContext,
    rows: Vec<ReducerClassSample>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.reducer_class_sample().insert(r),
        |id| {
            ctx.db.reducer_class_sample().sample_id().delete(id);
        },
        "reducer_class_sample",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_reducer_class_counter(
    ctx: &ReducerContext,
    rows: Vec<ReducerClassCounter>,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<String> = ctx
        .db
        .reducer_class_counter()
        .iter()
        .map(|r| r.class)
        .collect();
    for class in existing {
        ctx.db.reducer_class_counter().class().delete(class);
    }
    for row in rows {
        ctx.db.reducer_class_counter().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_floor_transition(
    ctx: &ReducerContext,
    rows: Vec<FloorTransition>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.floor_transition().insert(r),
        |id| {
            ctx.db.floor_transition().transition_id().delete(id);
        },
        "floor_transition",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_placed_object(
    ctx: &ReducerContext,
    rows: Vec<PlacedObject>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.placed_object().insert(r),
        |id| {
            ctx.db.placed_object().object_id().delete(id);
        },
        "placed_object",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_room(
    ctx: &ReducerContext,
    rows: Vec<Room>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.room().insert(r),
        |id| {
            ctx.db.room().room_id().delete(id);
        },
        "room",
        sequence_floor,
    )
}

#[spacetimedb::reducer]
pub fn restore_room_area(
    ctx: &ReducerContext,
    rows: Vec<RoomArea>,
    sequence_floor: u64,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    restore_autoinc_rows(
        rows,
        |r| ctx.db.room_area().insert(r),
        |id| {
            ctx.db.room_area().area_id().delete(id);
        },
        "room_area",
        sequence_floor,
    )
}

// --- direct insert: not auto_inc, not init-seeded, so `begin_restore`
// already guaranteed the table is empty -------------------------------
#[spacetimedb::reducer]
pub fn restore_citizen_state(ctx: &ReducerContext, rows: Vec<CitizenState>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    for row in rows {
        ctx.db.citizen_state().insert(row);
    }
    Ok(())
}

// --- replace: init-seeded (module_owner, the code tables), plus
// cadence_liveness (init-armed, not init-seeded, but the same reason:
// a real fire can write it before begin_restore ever runs) -- restore
// deletes what is already there, then inserts the exported rows -------
#[spacetimedb::reducer]
pub fn restore_module_owner(ctx: &ReducerContext, rows: Vec<ModuleOwner>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    // The module's own guard against locking the operator out, not only
    // restore-world.sh's early, friendlier message (Tim's direction):
    // an empty or foreign `module_owner.jsonl` must never be allowed to
    // delete the only owner this reducer is about to remove.
    match rows.as_slice() {
        [row] if row.owner == ctx.sender() => {}
        [row] => {
            return Err(format!(
                "restore_module_owner refuses to restore an owner ({}) that is not the caller ({}) -- require_owner would lock the operator out of the restored world",
                row.owner,
                ctx.sender()
            ));
        }
        other => {
            return Err(format!(
                "restore_module_owner requires exactly one row, got {}",
                other.len()
            ));
        }
    }
    let existing: Vec<u8> = ctx.db.module_owner().iter().map(|r| r.id).collect();
    for id in existing {
        ctx.db.module_owner().id().delete(id);
    }
    for row in rows {
        ctx.db.module_owner().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_world_clock(ctx: &ReducerContext, rows: Vec<WorldClock>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    // Exactly one row, keyed 0: an empty export must never delete the only epoch.
    if rows.len() != 1 {
        return Err(format!(
            "restore_world_clock requires exactly one row, got {}",
            rows.len()
        ));
    }
    if let Some(row) = rows.iter().find(|r| r.id != 0) {
        return Err(format!(
            "restore_world_clock requires id 0 (the one-row table's key), got {}",
            row.id
        ));
    }
    let existing: Vec<u8> = ctx.db.world_clock().iter().map(|r| r.id).collect();
    for id in existing {
        ctx.db.world_clock().id().delete(id);
    }
    for row in rows {
        ctx.db.world_clock().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_matter_kind(ctx: &ReducerContext, rows: Vec<MatterKind>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.matter_kind().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.matter_kind().code().delete(code);
    }
    for row in rows {
        ctx.db.matter_kind().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_provision(ctx: &ReducerContext, rows: Vec<Provision>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.provision().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.provision().code().delete(code);
    }
    for row in rows {
        ctx.db.provision().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_reason_code(ctx: &ReducerContext, rows: Vec<ReasonCode>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.reason_code().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.reason_code().code().delete(code);
    }
    for row in rows {
        ctx.db.reason_code().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_node_kind(ctx: &ReducerContext, rows: Vec<NodeKind>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.node_kind().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.node_kind().code().delete(code);
    }
    for row in rows {
        ctx.db.node_kind().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_unit(ctx: &ReducerContext, rows: Vec<Unit>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.unit().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.unit().code().delete(code);
    }
    for row in rows {
        ctx.db.unit().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_holder_kind(ctx: &ReducerContext, rows: Vec<HolderKind>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.holder_kind().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.holder_kind().code().delete(code);
    }
    for row in rows {
        ctx.db.holder_kind().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_layer_code(ctx: &ReducerContext, rows: Vec<LayerCode>) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx.db.layer_code().iter().map(|r| r.code).collect();
    for code in existing {
        ctx.db.layer_code().code().delete(code);
    }
    for row in rows {
        ctx.db.layer_code().insert(row);
    }
    Ok(())
}

#[spacetimedb::reducer]
pub fn restore_cadence_liveness(
    ctx: &ReducerContext,
    rows: Vec<CadenceLiveness>,
) -> Result<(), String> {
    count_call(ctx, ReducerClass::Operator);
    require_owner(ctx)?;
    require_restore_open(ctx)?;
    let existing: Vec<u32> = ctx
        .db
        .cadence_liveness()
        .iter()
        .map(|r| r.cadence)
        .collect();
    for cadence in existing {
        ctx.db.cadence_liveness().cadence().delete(cadence);
    }
    for row in rows {
        ctx.db.cadence_liveness().insert(row);
    }
    Ok(())
}
