// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as SyncClockProcedure from "../sync_clock_procedure";

export type SyncClockArgs = __Infer<typeof SyncClockProcedure.params>;
export type SyncClockResult = __Infer<typeof SyncClockProcedure.returnType>;

