// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptOidcIssuerReducer from "../accept_oidc_issuer_reducer";
import BeginLinkReducer from "../begin_link_reducer";
import BeginRestoreReducer from "../begin_restore_reducer";
import CompleteLinkReducer from "../complete_link_reducer";
import CreateCharacterReducer from "../create_character_reducer";
import CreateDistrictReducer from "../create_district_reducer";
import FinishPublishReducer from "../finish_publish_reducer";
import FinishRestoreReducer from "../finish_restore_reducer";
import RestoreBuildingReducer from "../restore_building_reducer";
import RestoreBuildingAreaReducer from "../restore_building_area_reducer";
import RestoreBusinessReducer from "../restore_business_reducer";
import RestoreCadenceLivenessReducer from "../restore_cadence_liveness_reducer";
import RestoreCharacterReducer from "../restore_character_reducer";
import RestoreCharacterIdentityReducer from "../restore_character_identity_reducer";
import RestoreCitizenReducer from "../restore_citizen_reducer";
import RestoreCitizenStateReducer from "../restore_citizen_state_reducer";
import RestoreContainerKindReducer from "../restore_container_kind_reducer";
import RestoreDemoPingReducer from "../restore_demo_ping_reducer";
import RestoreDistrictReducer from "../restore_district_reducer";
import RestoreFloorTransitionReducer from "../restore_floor_transition_reducer";
import RestoreHolderKindReducer from "../restore_holder_kind_reducer";
import RestoreItemHeldReducer from "../restore_item_held_reducer";
import RestoreItemInstanceReducer from "../restore_item_instance_reducer";
import RestoreItemPlacedReducer from "../restore_item_placed_reducer";
import RestoreLayerCodeReducer from "../restore_layer_code_reducer";
import RestoreLinkRequestReducer from "../restore_link_request_reducer";
import RestoreMatterKindReducer from "../restore_matter_kind_reducer";
import RestoreModuleOwnerReducer from "../restore_module_owner_reducer";
import RestoreNodeKindReducer from "../restore_node_kind_reducer";
import RestoreOidcIssuerReducer from "../restore_oidc_issuer_reducer";
import RestorePlacedObjectReducer from "../restore_placed_object_reducer";
import RestoreProvisionReducer from "../restore_provision_reducer";
import RestoreReasonCodeReducer from "../restore_reason_code_reducer";
import RestoreReducerClassCounterReducer from "../restore_reducer_class_counter_reducer";
import RestoreReducerClassSampleReducer from "../restore_reducer_class_sample_reducer";
import RestoreRoomReducer from "../restore_room_reducer";
import RestoreRoomAreaReducer from "../restore_room_area_reducer";
import RestoreStockReducer from "../restore_stock_reducer";
import RestoreStorageSampleReducer from "../restore_storage_sample_reducer";
import RestoreTableSampleReducer from "../restore_table_sample_reducer";
import RestoreUnitReducer from "../restore_unit_reducer";
import RestoreWorldClockReducer from "../restore_world_clock_reducer";
import SendPingReducer from "../send_ping_reducer";

export type AcceptOidcIssuerParams = __Infer<typeof AcceptOidcIssuerReducer>;
export type BeginLinkParams = __Infer<typeof BeginLinkReducer>;
export type BeginRestoreParams = __Infer<typeof BeginRestoreReducer>;
export type CompleteLinkParams = __Infer<typeof CompleteLinkReducer>;
export type CreateCharacterParams = __Infer<typeof CreateCharacterReducer>;
export type CreateDistrictParams = __Infer<typeof CreateDistrictReducer>;
export type FinishPublishParams = __Infer<typeof FinishPublishReducer>;
export type FinishRestoreParams = __Infer<typeof FinishRestoreReducer>;
export type RestoreBuildingParams = __Infer<typeof RestoreBuildingReducer>;
export type RestoreBuildingAreaParams = __Infer<typeof RestoreBuildingAreaReducer>;
export type RestoreBusinessParams = __Infer<typeof RestoreBusinessReducer>;
export type RestoreCadenceLivenessParams = __Infer<typeof RestoreCadenceLivenessReducer>;
export type RestoreCharacterParams = __Infer<typeof RestoreCharacterReducer>;
export type RestoreCharacterIdentityParams = __Infer<typeof RestoreCharacterIdentityReducer>;
export type RestoreCitizenParams = __Infer<typeof RestoreCitizenReducer>;
export type RestoreCitizenStateParams = __Infer<typeof RestoreCitizenStateReducer>;
export type RestoreContainerKindParams = __Infer<typeof RestoreContainerKindReducer>;
export type RestoreDemoPingParams = __Infer<typeof RestoreDemoPingReducer>;
export type RestoreDistrictParams = __Infer<typeof RestoreDistrictReducer>;
export type RestoreFloorTransitionParams = __Infer<typeof RestoreFloorTransitionReducer>;
export type RestoreHolderKindParams = __Infer<typeof RestoreHolderKindReducer>;
export type RestoreItemHeldParams = __Infer<typeof RestoreItemHeldReducer>;
export type RestoreItemInstanceParams = __Infer<typeof RestoreItemInstanceReducer>;
export type RestoreItemPlacedParams = __Infer<typeof RestoreItemPlacedReducer>;
export type RestoreLayerCodeParams = __Infer<typeof RestoreLayerCodeReducer>;
export type RestoreLinkRequestParams = __Infer<typeof RestoreLinkRequestReducer>;
export type RestoreMatterKindParams = __Infer<typeof RestoreMatterKindReducer>;
export type RestoreModuleOwnerParams = __Infer<typeof RestoreModuleOwnerReducer>;
export type RestoreNodeKindParams = __Infer<typeof RestoreNodeKindReducer>;
export type RestoreOidcIssuerParams = __Infer<typeof RestoreOidcIssuerReducer>;
export type RestorePlacedObjectParams = __Infer<typeof RestorePlacedObjectReducer>;
export type RestoreProvisionParams = __Infer<typeof RestoreProvisionReducer>;
export type RestoreReasonCodeParams = __Infer<typeof RestoreReasonCodeReducer>;
export type RestoreReducerClassCounterParams = __Infer<typeof RestoreReducerClassCounterReducer>;
export type RestoreReducerClassSampleParams = __Infer<typeof RestoreReducerClassSampleReducer>;
export type RestoreRoomParams = __Infer<typeof RestoreRoomReducer>;
export type RestoreRoomAreaParams = __Infer<typeof RestoreRoomAreaReducer>;
export type RestoreStockParams = __Infer<typeof RestoreStockReducer>;
export type RestoreStorageSampleParams = __Infer<typeof RestoreStorageSampleReducer>;
export type RestoreTableSampleParams = __Infer<typeof RestoreTableSampleReducer>;
export type RestoreUnitParams = __Infer<typeof RestoreUnitReducer>;
export type RestoreWorldClockParams = __Infer<typeof RestoreWorldClockReducer>;
export type SendPingParams = __Infer<typeof SendPingReducer>;

