// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const PlacedObject = __t.object("PlacedObject", {
  objectId: __t.u64(),
  defId: __t.u32(),
  x: __t.i32(),
  y: __t.i32(),
  floor: __t.i8(),
  layer: __t.u32(),
  orientation: __t.u8(),
  chunkKey: __t.u64(),
});
export type PlacedObject = __Infer<typeof PlacedObject>;

