// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ClearReducer from "../clear_reducer";
import SeedRowsReducer from "../seed_rows_reducer";

export type ClearParams = __Infer<typeof ClearReducer>;
export type SeedRowsParams = __Infer<typeof SeedRowsReducer>;

