// @generated by scripts/gen-protocol-version.sh -- do not edit by hand
// Regenerate: scripts/gen-protocol-version.sh

/**
 * A SHA-256 over every git-tracked file under `client/src/net/bindings/`
 * (the module's complete client-visible surface -- public tables, reducer
 * signatures, views, SDK codegen version), sorted by path, LF-normalised,
 * truncated to 16 hex characters -- the same idiom as `defs_version`
 * (`docs/architecture.md`). Compared against the server's own
 * `server/src/generated/protocol_version.rs` by the FR147 handshake; a
 * mismatch means the bindings compiled into this bundle disagree with
 * what the module actually publishes.
 */
export const PROTOCOL_VERSION = "18ccdc5598afe1bc";
