// Quentin's direction: pins that the server's and the client's
// independent parsers agree on every field, mechanically. This is the
// TypeScript side -- reads the committed `client/public/defs/defs.json`
// through this client's own `parseDefs`, and checks the canonical dump
// against the exact same committed golden `server/sim/tests/defs_dump.rs`
// reads from the Rust side's own compiled `sim::generated::defs` tables.
// Never regenerated by this test; a mismatch is exactly the moment a
// human must look.
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { canonicalDump, parseDefs } from "../../../src/defs/parse";

const REPO_ROOT = fileURLToPath(new URL("../../../../", import.meta.url));

describe("defs canonical dump", () => {
  it("matches the shared golden both parsers are checked against", () => {
    const defsJson = JSON.parse(
      readFileSync(`${REPO_ROOT}client/public/defs/defs.json`, "utf-8"),
    ) as unknown;
    const golden = readFileSync(`${REPO_ROOT}fixtures/defs-dump.v1.golden`, "utf-8");

    const defs = parseDefs(defsJson);

    expect(canonicalDump(defs)).toBe(golden);
  });
});
