//! A schema model built from `../src`'s own source text -- deliberately not
//! the compiled host schema (`browser_city` cannot be linked natively, see
//! `lib.rs`), and deliberately not a Rust parser, only a guard rail wide
//! enough to catch the mistakes NFR33-NFR37 exist to forbid: two primary
//! keys on one table, a table too wide to have been thought through, a
//! scheduled table missing its required shape, and (via
//! `server/schema.snapshot.json`, generated by the `regen-schema-snapshot`
//! binary and asserted current in `tests/schema_snapshot_current.rs`) any
//! primary key, unique constraint or scheduled status that moves after the
//! fact -- `scripts/ci/check-schema-additive.sh` diffs that snapshot
//! against the PR's merge base.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

/// One field of a `#[spacetimedb::table]` struct.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ColumnDef {
    pub name: String,
    pub ty: String,
    pub primary_key: bool,
    pub auto_inc: bool,
    pub unique: bool,
    /// `#[default(...)]` is present -- NFR33's escape hatch for appending a
    /// column to a table that already has live rows.
    pub has_default: bool,
}

/// One `#[spacetimedb::table(...)]` struct.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TableDef {
    pub accessor: String,
    pub struct_name: String,
    pub public: bool,
    /// `Some(reducer_name)` for a `scheduled(reducer_name)` table.
    pub scheduled_reducer: Option<String>,
    /// Present only when the struct's body carries a
    /// `// bc:wide-table: <reason>` waiver line (NFR35's only mechanical
    /// reading).
    pub wide_table_waiver: Option<String>,
    pub columns: Vec<ColumnDef>,
}

/// The whole module's table shape, sorted by accessor so the committed
/// snapshot's diff is never just filesystem walk order changing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ModuleSchema {
    pub tables: Vec<TableDef>,
}

impl ModuleSchema {
    /// Canonical, deterministic JSON -- `regen-schema-snapshot` writes
    /// exactly this, and `tests/schema_snapshot_current.rs` fails if the
    /// committed file differs from it by even trailing whitespace.
    pub fn to_pretty_json(&self) -> String {
        let mut json = serde_json::to_string_pretty(self).expect("ModuleSchema always serializes");
        json.push('\n');
        json
    }
}

/// `../src` relative to this crate -- stable regardless of the caller's own
/// working directory, since `CARGO_MANIFEST_DIR` is this crate's manifest
/// directory at compile time.
pub fn module_src_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("bounds crate has a parent directory")
        .join("src")
}

/// `../` relative to this crate, i.e. `server/` -- where
/// `schema.snapshot.json` lives.
pub fn module_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("bounds crate has a parent directory")
        .to_path_buf()
}

fn rust_files_under(dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|e| e.expect("dir entry").path())
        .collect();
    // Sorted: `fs::read_dir` order is not guaranteed, and the snapshot's
    // whole point is a stable diff.
    entries.sort();
    for path in entries {
        if path.is_dir() {
            rust_files_under(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

/// Every `.rs` file's text under `dir`, in a stable (sorted-path) order.
pub fn read_rust_files(dir: &Path) -> Vec<(PathBuf, String)> {
    let mut files = Vec::new();
    rust_files_under(dir, &mut files);
    files
        .into_iter()
        .map(|path| {
            let text = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            (path, text)
        })
        .collect()
}

/// Index just past the parenthesis balancing the one at `open` (which must
/// itself be `(`). Panics on unbalanced parens -- see
/// `registry_matches_tables.rs`'s copy of this rationale, which this
/// duplicates rather than shares across the test/lib boundary.
fn matching_paren_end(text: &str, open: usize) -> usize {
    let mut depth: i32 = 0;
    for (i, b) in text.as_bytes()[open..].iter().enumerate() {
        match b {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return open + i + 1;
                }
            }
            _ => {}
        }
    }
    panic!("unbalanced parentheses scanning a #[spacetimedb::table(...)] attribute");
}

/// Index just past the brace balancing the one at `open` (which must itself
/// be `{`).
fn matching_brace_end(text: &str, open: usize) -> usize {
    let mut depth: i32 = 0;
    for (i, b) in text.as_bytes()[open..].iter().enumerate() {
        match b {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return open + i + 1;
                }
            }
            _ => {}
        }
    }
    panic!("unbalanced braces scanning a #[spacetimedb::table(...)] struct body");
}

fn attr_has_token(attr: &str, token: &str) -> bool {
    attr.split(',').any(|part| part.trim() == token)
}

fn attr_value_after(attr: &str, key: &str) -> Option<String> {
    let at = attr.find(key)?;
    let after = &attr[at + key.len()..];
    let eq_at = after.find('=')?;
    let value = after[eq_at + 1..]
        .trim_start()
        .split(|c: char| c == ',' || c.is_whitespace() || c == ')')
        .next()
        .unwrap_or("");
    if value.is_empty() {
        None
    } else {
        Some(value.to_string())
    }
}

fn scheduled_reducer_in(attr: &str) -> Option<String> {
    let at = attr.find("scheduled(")?;
    let open = at + "scheduled".len();
    let close = matching_paren_end(attr, open);
    let inner = attr[open + 1..close - 1].trim();
    if inner.is_empty() {
        None
    } else {
        Some(inner.to_string())
    }
}

/// Parses one field chunk (its `#[...]` attributes plus `[pub] name: Type`)
/// into a [`ColumnDef`]. `chunk` has already been split on a top-level
/// comma by [`split_fields`].
fn parse_field(chunk: &str) -> Option<ColumnDef> {
    let mut primary_key = false;
    let mut auto_inc = false;
    let mut unique = false;
    let mut has_default = false;

    let mut rest = chunk.trim();
    while let Some(stripped) = rest.trim_start().strip_prefix("#[") {
        let close = stripped.find(']')?;
        let attr = &stripped[..close];
        let attr_name = attr.split(['(', ' ']).next().unwrap_or("").trim();
        match attr_name {
            "primary_key" => primary_key = true,
            "auto_inc" => auto_inc = true,
            "unique" => unique = true,
            "default" => has_default = true,
            _ => {}
        }
        rest = &stripped[close + 1..];
    }

    let rest = rest.trim();
    // Strip a leading doc comment or blank remainder (a trailing comma
    // produces an empty final chunk).
    if rest.is_empty() {
        return None;
    }
    let rest = rest.strip_prefix("pub ").unwrap_or(rest).trim();
    let colon_at = rest.find(':')?;
    let name = rest[..colon_at].trim().to_string();
    let ty = rest[colon_at + 1..].trim().trim_end_matches(',').trim();
    if name.is_empty() || ty.is_empty() {
        return None;
    }

    Some(ColumnDef {
        name,
        ty: ty.to_string(),
        primary_key,
        auto_inc,
        unique,
        has_default,
    })
}

/// Splits a struct body into per-field chunks (attributes + declaration),
/// on commas at bracket depth zero -- so a `Vec<(u32, u32)>` field type or
/// an `#[index(btree(columns = [a, b]))]` attribute never gets sliced in
/// the middle.
fn split_fields(body: &str) -> Vec<&str> {
    let mut chunks = Vec::new();
    let mut depth: i32 = 0;
    let mut start = 0usize;
    let bytes = body.as_bytes();
    for (i, b) in bytes.iter().enumerate() {
        match b {
            b'(' | b'[' | b'{' | b'<' => depth += 1,
            b')' | b']' | b'}' | b'>' => depth -= 1,
            b',' if depth == 0 => {
                chunks.push(&body[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < body.len() {
        chunks.push(&body[start..]);
    }
    chunks
}

fn strip_line_comments(text: &str) -> String {
    text.lines()
        .map(|line| match line.find("//") {
            Some(at) => &line[..at],
            None => line,
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Every `#[spacetimedb::table(...)] pub struct Name { ... }` in `text`.
fn tables_in(text: &str) -> Vec<TableDef> {
    let mut tables = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("#[spacetimedb::table(") {
        let open = at + "#[spacetimedb::table".len();
        let close = matching_paren_end(rest, open);
        let attr = &rest[open + 1..close - 1];

        let accessor = attr_value_after(attr, "accessor").unwrap_or_default();
        let public = attr_has_token(attr, "public");
        let scheduled_reducer = scheduled_reducer_in(attr);

        // Find the struct that follows: skip to `struct`, then its name,
        // then its `{...}` body. Every offset from here on is relative to
        // `after_struct_kw`, so `rest` can simply be re-sliced from it at
        // the end -- no separate absolute-position bookkeeping to get
        // wrong.
        let after_attr = &rest[close..];
        let struct_kw_at = after_attr.find("struct ").unwrap_or_else(|| {
            panic!(
                "no `struct` follows a #[spacetimedb::table(accessor = {accessor}, ...)] attribute"
            )
        });
        let after_struct_kw = &after_attr[struct_kw_at + "struct ".len()..];
        let name_end = after_struct_kw.find(['{', '(']).unwrap_or_else(|| {
            panic!("could not find struct body after `struct` for table `{accessor}`")
        });
        let struct_name = after_struct_kw[..name_end].trim().to_string();
        let body_open_rel = after_struct_kw[name_end..]
            .find('{')
            .unwrap_or_else(|| panic!("struct {struct_name} has no braced body"));
        let body_open = name_end + body_open_rel;
        let body_close = matching_brace_end(after_struct_kw, body_open);
        let raw_body = &after_struct_kw[body_open + 1..body_close - 1];

        let wide_table_waiver = raw_body.lines().find_map(|line| {
            line.trim()
                .strip_prefix("// bc:wide-table:")
                .map(|reason| reason.trim().to_string())
        });

        let body = strip_line_comments(raw_body);
        let columns = split_fields(&body)
            .into_iter()
            .filter_map(parse_field)
            .collect();

        tables.push(TableDef {
            accessor,
            struct_name,
            public,
            scheduled_reducer,
            wide_table_waiver,
            columns,
        });

        rest = &after_struct_kw[body_close..];
    }
    tables
}

/// Every `#[spacetimedb::reducer...] pub fn <name>` in `text` -- a guard
/// rail, not a parser: it accepts a false positive (a `fn` that merely
/// follows a reducer attribute textually within the same item) far more
/// readily than it would accept a false negative.
pub fn reducer_names_in(text: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("#[spacetimedb::reducer") {
        let after = &rest[at..];
        if let Some(fn_at) = after.find("fn ") {
            let after_fn = &after[fn_at + "fn ".len()..];
            let name_end = after_fn.find('(').unwrap_or(after_fn.len());
            names.push(after_fn[..name_end].trim().to_string());
            rest = &after[fn_at + 3..];
        } else {
            rest = &after[1..];
        }
    }
    names
}

/// Builds the whole module's schema model from every `.rs` file under
/// `src_dir`, sorted by accessor.
pub fn parse_module_schema(src_dir: &Path) -> ModuleSchema {
    let mut tables = Vec::new();
    for (_path, text) in read_rust_files(src_dir) {
        tables.extend(tables_in(&text));
    }
    tables.sort_by(|a, b| a.accessor.cmp(&b.accessor));
    ModuleSchema { tables }
}

/// Every reducer named anywhere under `src_dir`.
pub fn reducer_names_in_dir(src_dir: &Path) -> Vec<String> {
    let mut names = Vec::new();
    for (_path, text) in read_rust_files(src_dir) {
        names.extend(reducer_names_in(&text));
    }
    names
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_one_simple_table() {
        let src = "#[spacetimedb::table(accessor = person)]\n\
                   pub struct Person {\n    #[primary_key]\n    #[auto_inc]\n    pub id: u64,\n    pub name: String,\n}";
        let tables = tables_in(src);
        assert_eq!(tables.len(), 1);
        let t = &tables[0];
        assert_eq!(t.accessor, "person");
        assert_eq!(t.struct_name, "Person");
        assert!(!t.public);
        assert_eq!(t.scheduled_reducer, None);
        assert_eq!(t.columns.len(), 2);
        assert_eq!(t.columns[0].name, "id");
        assert_eq!(t.columns[0].ty, "u64");
        assert!(t.columns[0].primary_key);
        assert!(t.columns[0].auto_inc);
        assert_eq!(t.columns[1].name, "name");
        assert_eq!(t.columns[1].ty, "String");
        assert!(!t.columns[1].primary_key);
    }

    #[test]
    fn parses_public_unique_and_default_and_scheduled() {
        let src = "#[spacetimedb::table(accessor = tick_timer, scheduled(tick), public)]\n\
                   pub struct TickTimer {\n\
                   #[primary_key]\n#[auto_inc]\npub scheduled_id: u64,\n\
                   pub scheduled_at: spacetimedb::ScheduleAt,\n\
                   #[unique]\npub owner: Identity,\n\
                   #[default(0)]\npub extra: u32,\n\
                   }";
        let tables = tables_in(src);
        assert_eq!(tables.len(), 1);
        let t = &tables[0];
        assert!(t.public);
        assert_eq!(t.scheduled_reducer.as_deref(), Some("tick"));
        assert_eq!(t.columns.len(), 4);
        assert!(t.columns[2].unique);
        assert!(t.columns[3].has_default);
    }

    #[test]
    fn finds_two_tables_in_one_file() {
        let src = "#[spacetimedb::table(accessor = a)]\npub struct A { #[primary_key] pub id: u64 }\n\
                   #[spacetimedb::table(accessor = b, public)]\npub struct B { #[primary_key] pub id: u64 }";
        let tables = tables_in(src);
        assert_eq!(tables.len(), 2);
        assert_eq!(tables[0].accessor, "a");
        assert_eq!(tables[1].accessor, "b");
    }

    #[test]
    fn captures_a_wide_table_waiver_comment() {
        let src = "#[spacetimedb::table(accessor = wide)]\n\
                   pub struct Wide {\n\
                   // bc:wide-table: this table intentionally carries every field a citizen needs read in one query\n\
                   #[primary_key]\npub id: u64,\n}";
        let tables = tables_in(src);
        assert_eq!(
            tables[0].wide_table_waiver.as_deref(),
            Some("this table intentionally carries every field a citizen needs read in one query")
        );
    }

    #[test]
    fn reducer_names_in_finds_a_stubbed_reducer() {
        let src = "#[spacetimedb::reducer]\npub fn run_tick(ctx: &ReducerContext, _row: TickTimer) -> Result<(), String> { Ok(()) }";
        assert_eq!(reducer_names_in(src), vec!["run_tick".to_string()]);
    }

    #[test]
    fn reducer_names_in_finds_an_annotated_lifecycle_reducer() {
        let src = "#[spacetimedb::reducer(init)]\npub fn init(_ctx: &ReducerContext) {}";
        assert_eq!(reducer_names_in(src), vec!["init".to_string()]);
    }

    #[test]
    fn to_pretty_json_round_trips() {
        let schema = ModuleSchema {
            tables: vec![TableDef {
                accessor: "a".to_string(),
                struct_name: "A".to_string(),
                public: false,
                scheduled_reducer: None,
                wide_table_waiver: None,
                columns: vec![ColumnDef {
                    name: "id".to_string(),
                    ty: "u64".to_string(),
                    primary_key: true,
                    auto_inc: true,
                    unique: false,
                    has_default: false,
                }],
            }],
        };
        let json = schema.to_pretty_json();
        let parsed: ModuleSchema = serde_json::from_str(&json).expect("valid json");
        assert_eq!(parsed, schema);
    }
}
