#!/usr/bin/env bash
# Generates server/src/generated/protocol_version.rs and client/src/net/
# protocol-version.ts from a SHA-256 over every git-tracked file under
# client/src/net/bindings/ -- the module's complete client-visible surface
# (public tables, reducer signatures, views, SDK codegen version) -- sorted
# by path, LF-normalised, truncated to 16 hex characters: the same idiom
# `defs_version` uses (docs/architecture.md, tools/defs-build/src/
# version.rs), reimplemented here in plain shell (no dependency of its
# own) because tools/defs-build reads only defs/ and nothing else.
#
# Never run by either build target: a check, not a build step.
# scripts/ci/check-bindings-current.sh regenerates the bindings and both
# outputs here in the same run and diffs all three against what is
# committed; that is the only thing that keeps this honest. Byte-identical
# on Windows and Linux checkouts -- every input is read raw and LF-
# normalised before hashing, so the checkout's own line-ending translation
# never changes the result.
set -euo pipefail
REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BINDINGS_DIR="client/src/net/bindings"
RUST_OUT="server/src/generated/protocol_version.rs"
TS_OUT="client/src/net/protocol-version.ts"
VERSION_LEN=16

[ -d "$BINDINGS_DIR" ] || {
  echo "gen-protocol-version: $BINDINGS_DIR not found" >&2
  exit 1
}

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
BUF="$WORK/buf"
NORM="$WORK/norm"
: >"$BUF"

# git ls-files already emits forward-slash paths, sorted with `sort`
# below by path bytes -- matching tools/defs-build/src/version.rs's own
# normalisation exactly.
while IFS= read -r path; do
  [ -n "$path" ] || continue
  tr -d '\r' <"$path" >"$NORM"
  size="$(wc -c <"$NORM" | tr -d '[:space:]')"
  printf '%s\0%s\0' "$path" "$size" >>"$BUF"
  cat "$NORM" >>"$BUF"
  printf '\n' >>"$BUF"
done < <(git ls-files -- "$BINDINGS_DIR" | LC_ALL=C sort)

digest="$(sha256sum "$BUF" | cut -d' ' -f1)"
version="${digest:0:$VERSION_LEN}"

mkdir -p "$(dirname "$RUST_OUT")"
cat >"$RUST_OUT" <<EOF
// @generated by scripts/gen-protocol-version.sh -- do not edit by hand
// Regenerate: scripts/gen-protocol-version.sh

/// A SHA-256 over every git-tracked file under the generated TypeScript
/// SDK bindings directory (the module's complete client-visible surface --
/// public tables, reducer signatures, views, SDK codegen version), sorted
/// by path, LF-normalised, truncated to 16 hex characters -- the same
/// idiom as \`defs_version\` (\`docs/architecture.md\`). Compared against the
/// client's own copy of this same constant by the FR147 handshake; a
/// mismatch means the bindings compiled into the client's bundle disagree
/// with what the module actually publishes.
pub const PROTOCOL_VERSION: &str = "$version";
EOF

cat >"$TS_OUT" <<EOF
// @generated by scripts/gen-protocol-version.sh -- do not edit by hand
// Regenerate: scripts/gen-protocol-version.sh

/**
 * A SHA-256 over every git-tracked file under \`client/src/net/bindings/\`
 * (the module's complete client-visible surface -- public tables, reducer
 * signatures, views, SDK codegen version), sorted by path, LF-normalised,
 * truncated to 16 hex characters -- the same idiom as \`defs_version\`
 * (\`docs/architecture.md\`). Compared against the server's own
 * \`server/src/generated/protocol_version.rs\` by the FR147 handshake; a
 * mismatch means the bindings compiled into this bundle disagree with
 * what the module actually publishes.
 */
export const PROTOCOL_VERSION = "$version";
EOF

echo "gen-protocol-version: PROTOCOL_VERSION = $version" >&2
