//! Stage 3 of `parse, validate, emit`: renders the validated [`Defs`] tree
//! as byte-stable text -- never shells out to `rustfmt`, sorts every
//! collection by its declared key (already done by `validate.rs`), writes
//! LF only (Tim's direction) -- for both consumers. Pure: returns
//! `String`s; the binary's own edge writes them to disk.

use crate::model::Defs;

pub const GENERATED_HEADER_RUST: &str = "// @generated by tools/defs-build -- do not edit by hand";

/// `client/public/defs/defs.json` has no comment syntax to carry the same
/// header as a first *line*, so it carries it as the first *field* of the
/// document instead -- the closest equivalent for a JSON artefact.
pub const GENERATED_FIELD_JSON: &str = "tools/defs-build -- do not edit by hand";

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn json_str_array(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| json_escape(s)).collect();
    format!("[{}]", inner.join(","))
}

/// Renders `server/sim/src/generated/defs.rs`: `static`/`const` tables of
/// plain structs over `&'static str` and integers only -- no
/// deserialisation, no allocation, no `serde` at runtime (Tim's
/// direction).
pub fn emit_rust(defs: &Defs, defs_version: &str) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER_RUST);
    out.push('\n');
    out.push_str("// Regenerate: cargo run --manifest-path tools/defs-build/Cargo.toml\n\n");
    out.push_str(&format!(
        "pub const DEFS_VERSION: &str = {:?};\n\n",
        defs_version
    ));

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ObjectDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub width: u32,\n    pub height: u32,\n}\n\n");
    out.push_str("pub const OBJECTS: &[ObjectDef] = &[\n");
    for o in &defs.objects {
        out.push_str(&format!(
            "    ObjectDef {{ id: {}, key: {:?}, width: {}, height: {} }},\n",
            o.id, o.key, o.width, o.height
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ItemDef {\n    pub id: u32,\n    pub key: &'static str,\n}\n\n");
    out.push_str("pub const ITEMS: &[ItemDef] = &[\n");
    for i in &defs.items {
        out.push_str(&format!(
            "    ItemDef {{ id: {}, key: {:?} }},\n",
            i.id, i.key
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct RecipeDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub inputs: &'static [&'static str],\n    pub outputs: &'static [&'static str],\n}\n\n");
    out.push_str("pub const RECIPES: &[RecipeDef] = &[\n");
    for r in &defs.recipes {
        let inputs = fmt_str_slice(&r.inputs);
        let outputs = fmt_str_slice(&r.outputs);
        out.push_str(&format!(
            "    RecipeDef {{ id: {}, key: {:?}, inputs: &{}, outputs: &{} }},\n",
            r.id, r.key, inputs, outputs
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ProfessionDef {\n    pub id: u32,\n    pub key: &'static str,\n}\n\n");
    out.push_str("pub const PROFESSIONS: &[ProfessionDef] = &[\n");
    for p in &defs.professions {
        out.push_str(&format!(
            "    ProfessionDef {{ id: {}, key: {:?} }},\n",
            p.id, p.key
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ChainDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub links: &'static [&'static str],\n}\n\n");
    out.push_str("pub const CHAINS: &[ChainDef] = &[\n");
    for c in &defs.chains {
        let links = fmt_str_slice(&c.links);
        out.push_str(&format!(
            "    ChainDef {{ id: {}, key: {:?}, links: &{} }},\n",
            c.id, c.key, links
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct BalanceSeed {\n    pub key: &'static str,\n    pub value: i64,\n    pub min: i64,\n    pub max: i64,\n}\n\n");
    out.push_str("pub const BALANCE: &[BalanceSeed] = &[\n");
    for b in &defs.balance {
        out.push_str(&format!(
            "    BalanceSeed {{ key: {:?}, value: {}, min: {}, max: {} }},\n",
            b.key, b.value, b.min, b.max
        ));
    }
    out.push_str("];\n");

    out
}

fn fmt_str_slice(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| format!("{s:?}")).collect();
    format!("[{}]", inner.join(", "))
}

/// Renders `client/public/defs/defs.json`: canonical JSON (fixed top-level
/// key order so the generated-file marker and `defs_version` are always
/// the first two fields; every entry's own fields sorted alphabetically),
/// LF only, no trailing whitespace.
pub fn emit_json(defs: &Defs, defs_version: &str) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!(
        "  \"generated_by\": {},\n",
        json_escape(GENERATED_FIELD_JSON)
    ));
    out.push_str(&format!(
        "  \"defs_version\": {},\n",
        json_escape(defs_version)
    ));

    out.push_str("  \"objects\": [\n");
    for (i, o) in defs.objects.iter().enumerate() {
        let comma = if i + 1 < defs.objects.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"height\": {}, \"id\": {}, \"key\": {}, \"width\": {} }}{comma}\n",
            o.height,
            o.id,
            json_escape(&o.key),
            o.width
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"items\": [\n");
    for (i, it) in defs.items.iter().enumerate() {
        let comma = if i + 1 < defs.items.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"key\": {} }}{comma}\n",
            it.id,
            json_escape(&it.key)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"recipes\": [\n");
    for (i, r) in defs.recipes.iter().enumerate() {
        let comma = if i + 1 < defs.recipes.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"inputs\": {}, \"key\": {}, \"outputs\": {} }}{comma}\n",
            r.id,
            json_str_array(&r.inputs),
            json_escape(&r.key),
            json_str_array(&r.outputs)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"professions\": [\n");
    for (i, p) in defs.professions.iter().enumerate() {
        let comma = if i + 1 < defs.professions.len() {
            ","
        } else {
            ""
        };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"key\": {} }}{comma}\n",
            p.id,
            json_escape(&p.key)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"chains\": [\n");
    for (i, c) in defs.chains.iter().enumerate() {
        let comma = if i + 1 < defs.chains.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"key\": {}, \"links\": {} }}{comma}\n",
            c.id,
            json_escape(&c.key),
            json_str_array(&c.links)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"balance\": [\n");
    for (i, b) in defs.balance.iter().enumerate() {
        let comma = if i + 1 < defs.balance.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"key\": {}, \"max\": {}, \"min\": {}, \"value\": {} }}{comma}\n",
            json_escape(&b.key),
            b.max,
            b.min,
            b.value
        ));
    }
    out.push_str("  ]\n");

    out.push_str("}\n");
    out
}

/// The append-only `kind id key` manifest `tools/defs-build/goldens/
/// defs-manifest.golden` pins -- balance excluded (Tim's direction: it
/// carries no id in this story). Grouped by kind in the same fixed order
/// as `emit_rust`, sorted by id within each kind (never by key, so a
/// rename never reorders these lines and never reads as a renumbering).
pub fn emit_id_manifest(defs: &Defs) -> String {
    let mut lines = Vec::new();
    let mut objects = defs.objects.clone();
    objects.sort_by_key(|o| o.id);
    for o in &objects {
        lines.push(format!("object {} {}", o.id, o.key));
    }
    let mut items = defs.items.clone();
    items.sort_by_key(|i| i.id);
    for i in &items {
        lines.push(format!("item {} {}", i.id, i.key));
    }
    let mut recipes = defs.recipes.clone();
    recipes.sort_by_key(|r| r.id);
    for r in &recipes {
        lines.push(format!("recipe {} {}", r.id, r.key));
    }
    let mut professions = defs.professions.clone();
    professions.sort_by_key(|p| p.id);
    for p in &professions {
        lines.push(format!("profession {} {}", p.id, p.key));
    }
    let mut chains = defs.chains.clone();
    chains.sort_by_key(|c| c.id);
    for c in &chains {
        lines.push(format!("chain {} {}", c.id, c.key));
    }
    let mut text = lines.join("\n");
    text.push('\n');
    text
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::*;

    fn sample() -> Defs {
        Defs {
            objects: vec![ObjectDef {
                id: 1,
                key: "trash-bin".into(),
                width: 1,
                height: 1,
            }],
            items: vec![ItemDef {
                id: 1,
                key: "bottle".into(),
            }],
            recipes: vec![RecipeDef {
                id: 1,
                key: "bottle-recycling".into(),
                inputs: vec!["bottle".into()],
                outputs: vec![],
            }],
            professions: vec![ProfessionDef {
                id: 1,
                key: "sanitation-worker".into(),
            }],
            chains: vec![ChainDef {
                id: 1,
                key: "plastic-bottle".into(),
                links: vec!["sanitation-worker".into()],
            }],
            balance: vec![BalanceDef {
                key: "citizen.bar_decay.rest".into(),
                value: 10,
                min: 0,
                max: 100,
            }],
        }
    }

    #[test]
    fn emit_rust_opens_with_the_generated_header_and_carries_the_version() {
        let out = emit_rust(&sample(), "abc123");
        assert!(out.starts_with(GENERATED_HEADER_RUST));
        assert!(out.contains("pub const DEFS_VERSION: &str = \"abc123\";"));
        assert!(out.contains("ObjectDef { id: 1, key: \"trash-bin\", width: 1, height: 1 }"));
        assert!(!out.contains('\r'));
    }

    #[test]
    fn emit_json_opens_with_generated_by_then_defs_version() {
        let out = emit_json(&sample(), "abc123");
        let lines: Vec<&str> = out.lines().collect();
        assert!(lines[1].contains("\"generated_by\""));
        assert!(lines[2].contains("\"defs_version\": \"abc123\""));
        assert!(!out.contains('\r'));
    }

    #[test]
    fn emit_json_is_valid_enough_to_round_trip_by_eye_every_kind_present() {
        let out = emit_json(&sample(), "v1");
        for key in [
            "\"objects\"",
            "\"items\"",
            "\"recipes\"",
            "\"professions\"",
            "\"chains\"",
            "\"balance\"",
        ] {
            assert!(out.contains(key), "missing {key} in {out}");
        }
    }

    #[test]
    fn emit_id_manifest_excludes_balance_and_sorts_by_id_within_kind() {
        let mut defs = sample();
        defs.objects.push(ObjectDef {
            id: 0,
            key: "aardvark".into(),
            width: 1,
            height: 1,
        });
        let manifest = emit_id_manifest(&defs);
        let lines: Vec<&str> = manifest.lines().collect();
        assert_eq!(lines[0], "object 0 aardvark");
        assert_eq!(lines[1], "object 1 trash-bin");
        assert!(!manifest.contains("balance"));
    }
}
