//! Stage 3 of `parse, validate, emit`: renders the validated [`Defs`] tree
//! as byte-stable text -- never shells out to `rustfmt`, sorts every
//! collection by its declared key (already done by `validate.rs`), writes
//! LF only (Tim's direction) -- for both consumers. Pure: returns
//! `String`s; the binary's own edge writes them to disk.

use crate::model::{
    COLLIDER_SUBCELLS_PER_CELL, ColliderRect, Defs, INTERACT_AT_MAX_REACH_CELLS,
    MAX_FOOTPRINT_CELLS, SpriteRect,
};

pub const GENERATED_HEADER_RUST: &str = "// @generated by tools/defs-build -- do not edit by hand";

/// `client/public/defs/defs.json` has no comment syntax to carry the same
/// header as a first *line*, so it carries it as the first *field* of the
/// document instead -- the closest equivalent for a JSON artefact.
pub const GENERATED_FIELD_JSON: &str = "tools/defs-build -- do not edit by hand";

fn json_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn json_str_array(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| json_escape(s)).collect();
    format!("[{}]", inner.join(","))
}

/// Renders `server/sim/src/generated/defs.rs`: `static`/`const` tables of
/// plain structs over `&'static str` and integers only -- no
/// deserialisation, no allocation, no `serde` at runtime (Tim's
/// direction).
pub fn emit_rust(defs: &Defs, defs_version: &str) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER_RUST);
    out.push('\n');
    out.push_str("// Regenerate: cargo run --manifest-path tools/defs-build/Cargo.toml\n\n");
    out.push_str(&format!(
        "pub const DEFS_VERSION: &str = {:?};\n\n",
        defs_version
    ));

    out.push_str(&format!(
        "/// Sub-cells per cell, the fixed unit a `collider` rect is declared in.\npub const COLLIDER_SUBCELLS_PER_CELL: i32 = {COLLIDER_SUBCELLS_PER_CELL};\n\n"
    ));

    out.push_str(&format!(
        "/// How far beyond its own footprint an `interact_at` rect may reach, in whole cells.\npub const INTERACT_AT_MAX_REACH_CELLS: i32 = {INTERACT_AT_MAX_REACH_CELLS};\n\n"
    ));

    out.push_str(&format!(
        "/// FR127's cap: a footprint's width and height are each held to this.\npub const MAX_FOOTPRINT_CELLS: i32 = {MAX_FOOTPRINT_CELLS};\n\n"
    ));

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ColliderRect {\n    pub x0: i32,\n    pub y0: i32,\n    pub x1: i32,\n    pub y1: i32,\n}\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct SpriteRect {\n    pub sheet: &'static str,\n    pub x: u32,\n    pub y: u32,\n    pub w: u32,\n    pub h: u32,\n}\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ObjectDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub name: &'static str,\n    pub layer: u32,\n    pub sprite: SpriteRect,\n    pub width: u32,\n    pub height: u32,\n    pub collider: Option<ColliderRect>,\n    pub interact_at: Option<ColliderRect>,\n    pub window: bool,\n}\n\n");
    out.push_str("pub const OBJECTS: &[ObjectDef] = &[\n");
    for o in &defs.objects {
        out.push_str(&format!(
            "    ObjectDef {{ id: {}, key: {:?}, name: {:?}, layer: {}, sprite: {}, width: {}, height: {}, collider: {}, interact_at: {}, window: {} }},\n",
            o.id,
            o.key,
            o.name,
            o.layer,
            fmt_sprite_rust(&o.sprite),
            o.width,
            o.height,
            fmt_collider_rust(o.collider),
            fmt_collider_rust(o.interact_at),
            o.window
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ItemDef {\n    pub id: u32,\n    pub key: &'static str,\n}\n\n");
    out.push_str("pub const ITEMS: &[ItemDef] = &[\n");
    for i in &defs.items {
        out.push_str(&format!(
            "    ItemDef {{ id: {}, key: {:?} }},\n",
            i.id, i.key
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct RecipeDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub inputs: &'static [&'static str],\n    pub outputs: &'static [&'static str],\n}\n\n");
    out.push_str("pub const RECIPES: &[RecipeDef] = &[\n");
    for r in &defs.recipes {
        let inputs = fmt_str_slice(&r.inputs);
        let outputs = fmt_str_slice(&r.outputs);
        out.push_str(&format!(
            "    RecipeDef {{ id: {}, key: {:?}, inputs: &{}, outputs: &{} }},\n",
            r.id, r.key, inputs, outputs
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ProfessionDef {\n    pub id: u32,\n    pub key: &'static str,\n}\n\n");
    out.push_str("pub const PROFESSIONS: &[ProfessionDef] = &[\n");
    for p in &defs.professions {
        out.push_str(&format!(
            "    ProfessionDef {{ id: {}, key: {:?} }},\n",
            p.id, p.key
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct ChainDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub links: &'static [&'static str],\n}\n\n");
    out.push_str("pub const CHAINS: &[ChainDef] = &[\n");
    for c in &defs.chains {
        let links = fmt_str_slice(&c.links);
        out.push_str(&format!(
            "    ChainDef {{ id: {}, key: {:?}, links: &{} }},\n",
            c.id, c.key, links
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct BalanceSeed {\n    pub key: &'static str,\n    pub value: i64,\n    pub min: i64,\n    pub max: i64,\n}\n\n");
    out.push_str("pub const BALANCE: &[BalanceSeed] = &[\n");
    for b in &defs.balance {
        out.push_str(&format!(
            "    BalanceSeed {{ key: {:?}, value: {}, min: {}, max: {} }},\n",
            b.key, b.value, b.min, b.max
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum Family {\n    Adult,\n    Kid,\n}\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum Pool {\n    Civilian,\n    RoleOnly,\n    Costume,\n}\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct BodyDef {\n    pub id: u16,\n    pub key: &'static str,\n    pub family: Family,\n    pub sheet: &'static str,\n    pub pool: Pool,\n}\n\n");
    out.push_str("pub const BODIES: &[BodyDef] = &[\n");
    for b in &defs.bodies {
        out.push_str(&format!(
            "    BodyDef {{ id: {}, key: {:?}, family: {}, sheet: {:?}, pool: {} }},\n",
            b.id,
            b.key,
            fmt_family_rust(b.family),
            b.sheet,
            fmt_pool_rust(b.pool)
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct EyesDef {\n    pub id: u16,\n    pub key: &'static str,\n    pub family: Family,\n    pub sheet: &'static str,\n    pub pool: Pool,\n}\n\n");
    out.push_str("pub const EYES: &[EyesDef] = &[\n");
    for e in &defs.eyes {
        out.push_str(&format!(
            "    EyesDef {{ id: {}, key: {:?}, family: {}, sheet: {:?}, pool: {} }},\n",
            e.id,
            e.key,
            fmt_family_rust(e.family),
            e.sheet,
            fmt_pool_rust(e.pool)
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct HairstyleDef {\n    pub id: u16,\n    pub key: &'static str,\n    pub family: Family,\n    pub sheet: &'static str,\n    pub style: u32,\n    pub color: u32,\n    pub rare: bool,\n}\n\n");
    out.push_str("pub const HAIRSTYLES: &[HairstyleDef] = &[\n");
    for h in &defs.hairstyles {
        out.push_str(&format!(
            "    HairstyleDef {{ id: {}, key: {:?}, family: {}, sheet: {:?}, style: {}, color: {}, rare: {} }},\n",
            h.id,
            h.key,
            fmt_family_rust(h.family),
            h.sheet,
            h.style,
            h.color,
            h.rare
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct OutfitDef {\n    pub id: u16,\n    pub key: &'static str,\n    pub family: Family,\n    pub sheet: &'static str,\n    pub pool: Pool,\n    pub hides_hairstyle: bool,\n}\n\n");
    out.push_str("pub const OUTFITS: &[OutfitDef] = &[\n");
    for o in &defs.outfits {
        out.push_str(&format!(
            "    OutfitDef {{ id: {}, key: {:?}, family: {}, sheet: {:?}, pool: {}, hides_hairstyle: {} }},\n",
            o.id,
            o.key,
            fmt_family_rust(o.family),
            o.sheet,
            fmt_pool_rust(o.pool),
            o.hides_hairstyle
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum Slot {\n    Face,\n    Head,\n    Back,\n    Torso,\n    Hands,\n}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct AccessoryDef {\n    pub id: u16,\n    pub key: &'static str,\n    pub family: Family,\n    pub sheet: &'static str,\n    pub pool: Pool,\n    pub slot: Slot,\n}\n\n");
    out.push_str("pub const ACCESSORIES: &[AccessoryDef] = &[\n");
    for a in &defs.accessories {
        out.push_str(&format!(
            "    AccessoryDef {{ id: {}, key: {:?}, family: {}, sheet: {:?}, pool: {}, slot: {} }},\n",
            a.id,
            a.key,
            fmt_family_rust(a.family),
            a.sheet,
            fmt_pool_rust(a.pool),
            fmt_slot_rust(a.slot)
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct AppearanceLayoutRowDef {\n    pub animation: &'static str,\n    pub row: u32,\n    pub frames_per_direction: u32,\n}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct AppearanceLayoutDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub family: Family,\n    pub cell_width: u32,\n    pub cell_height: u32,\n    pub directions: &'static [&'static str],\n    pub rows: &'static [AppearanceLayoutRowDef],\n    pub accepted_sizes: &'static [(u32, u32)],\n}\n\n");
    out.push_str("pub const APPEARANCE_LAYOUTS: &[AppearanceLayoutDef] = &[\n");
    for l in &defs.appearance_layouts {
        let directions = fmt_str_slice(&l.directions);
        let rows: Vec<String> = l
            .rows
            .iter()
            .map(|r| {
                format!(
                    "AppearanceLayoutRowDef {{ animation: {:?}, row: {}, frames_per_direction: {} }}",
                    r.animation, r.row, r.frames_per_direction
                )
            })
            .collect();
        let accepted_sizes: Vec<String> = l
            .accepted_sizes
            .iter()
            .map(|(w, h)| format!("({w}, {h})"))
            .collect();
        out.push_str(&format!(
            "    AppearanceLayoutDef {{ id: {}, key: {:?}, family: {}, cell_width: {}, cell_height: {}, directions: &{}, rows: &[{}], accepted_sizes: &[{}] }},\n",
            l.id,
            l.key,
            fmt_family_rust(l.family),
            l.cell_width,
            l.cell_height,
            directions,
            rows.join(", "),
            accepted_sizes.join(", ")
        ));
    }
    out.push_str("];\n\n");

    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub struct UniformDef {\n    pub id: u32,\n    pub key: &'static str,\n    pub profession: &'static str,\n    pub outfit: Option<&'static str>,\n    pub accessory: Option<&'static str>,\n}\n\n");
    out.push_str("pub const UNIFORMS: &[UniformDef] = &[\n");
    for u in &defs.uniforms {
        out.push_str(&format!(
            "    UniformDef {{ id: {}, key: {:?}, profession: {:?}, outfit: {}, accessory: {} }},\n",
            u.id,
            u.key,
            u.profession,
            fmt_opt_str_rust(&u.outfit),
            fmt_opt_str_rust(&u.accessory)
        ));
    }
    out.push_str("];\n");

    out
}

fn fmt_family_rust(family: crate::model::Family) -> &'static str {
    match family {
        crate::model::Family::Adult => "Family::Adult",
        crate::model::Family::Kid => "Family::Kid",
    }
}

fn fmt_pool_rust(pool: crate::model::Pool) -> &'static str {
    match pool {
        crate::model::Pool::Civilian => "Pool::Civilian",
        crate::model::Pool::RoleOnly => "Pool::RoleOnly",
        crate::model::Pool::Costume => "Pool::Costume",
    }
}

fn fmt_slot_rust(slot: crate::model::Slot) -> &'static str {
    match slot {
        crate::model::Slot::Face => "Slot::Face",
        crate::model::Slot::Head => "Slot::Head",
        crate::model::Slot::Back => "Slot::Back",
        crate::model::Slot::Torso => "Slot::Torso",
        crate::model::Slot::Hands => "Slot::Hands",
    }
}

fn fmt_opt_str_rust(s: &Option<String>) -> String {
    match s {
        None => "None".to_string(),
        Some(v) => format!("Some({v:?})"),
    }
}

fn fmt_opt_str_json(s: &Option<String>) -> String {
    match s {
        None => "null".to_string(),
        Some(v) => json_escape(v),
    }
}

fn fmt_sprite_rust(sprite: &SpriteRect) -> String {
    format!(
        "SpriteRect {{ sheet: {:?}, x: {}, y: {}, w: {}, h: {} }}",
        sprite.sheet, sprite.x, sprite.y, sprite.w, sprite.h
    )
}

fn fmt_sprite_json(sprite: &SpriteRect) -> String {
    format!(
        "{{ \"sheet\": {}, \"x\": {}, \"y\": {}, \"w\": {}, \"h\": {} }}",
        json_escape(&sprite.sheet),
        sprite.x,
        sprite.y,
        sprite.w,
        sprite.h
    )
}

fn fmt_collider_rust(collider: Option<ColliderRect>) -> String {
    match collider {
        None => "None".to_string(),
        Some(c) => format!(
            "Some(ColliderRect {{ x0: {}, y0: {}, x1: {}, y1: {} }})",
            c.x0, c.y0, c.x1, c.y1
        ),
    }
}

fn fmt_collider_json(collider: Option<ColliderRect>) -> String {
    match collider {
        None => "null".to_string(),
        Some(c) => format!(
            "{{ \"x0\": {}, \"y0\": {}, \"x1\": {}, \"y1\": {} }}",
            c.x0, c.y0, c.x1, c.y1
        ),
    }
}

fn fmt_str_slice(items: &[String]) -> String {
    let inner: Vec<String> = items.iter().map(|s| format!("{s:?}")).collect();
    format!("[{}]", inner.join(", "))
}

/// Renders `client/public/defs/defs.json`: canonical JSON (fixed top-level
/// key order so the generated-file marker and `defs_version` are always
/// the first two fields; every entry's own fields sorted alphabetically),
/// LF only, no trailing whitespace.
pub fn emit_json(defs: &Defs, defs_version: &str) -> String {
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(&format!(
        "  \"generated_by\": {},\n",
        json_escape(GENERATED_FIELD_JSON)
    ));
    out.push_str(&format!(
        "  \"defs_version\": {},\n",
        json_escape(defs_version)
    ));
    out.push_str(&format!(
        "  \"collider_subcells_per_cell\": {COLLIDER_SUBCELLS_PER_CELL},\n"
    ));
    out.push_str(&format!(
        "  \"interact_at_max_reach_cells\": {INTERACT_AT_MAX_REACH_CELLS},\n"
    ));
    out.push_str(&format!(
        "  \"max_footprint_cells\": {MAX_FOOTPRINT_CELLS},\n"
    ));

    out.push_str("  \"objects\": [\n");
    for (i, o) in defs.objects.iter().enumerate() {
        let comma = if i + 1 < defs.objects.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"collider\": {}, \"height\": {}, \"id\": {}, \"interact_at\": {}, \"key\": {}, \"layer\": {}, \"name\": {}, \"sprite\": {}, \"width\": {}, \"window\": {} }}{comma}\n",
            fmt_collider_json(o.collider),
            o.height,
            o.id,
            fmt_collider_json(o.interact_at),
            json_escape(&o.key),
            o.layer,
            json_escape(&o.name),
            fmt_sprite_json(&o.sprite),
            o.width,
            o.window
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"items\": [\n");
    for (i, it) in defs.items.iter().enumerate() {
        let comma = if i + 1 < defs.items.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"key\": {} }}{comma}\n",
            it.id,
            json_escape(&it.key)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"recipes\": [\n");
    for (i, r) in defs.recipes.iter().enumerate() {
        let comma = if i + 1 < defs.recipes.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"inputs\": {}, \"key\": {}, \"outputs\": {} }}{comma}\n",
            r.id,
            json_str_array(&r.inputs),
            json_escape(&r.key),
            json_str_array(&r.outputs)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"professions\": [\n");
    for (i, p) in defs.professions.iter().enumerate() {
        let comma = if i + 1 < defs.professions.len() {
            ","
        } else {
            ""
        };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"key\": {} }}{comma}\n",
            p.id,
            json_escape(&p.key)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"chains\": [\n");
    for (i, c) in defs.chains.iter().enumerate() {
        let comma = if i + 1 < defs.chains.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"id\": {}, \"key\": {}, \"links\": {} }}{comma}\n",
            c.id,
            json_escape(&c.key),
            json_str_array(&c.links)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"balance\": [\n");
    for (i, b) in defs.balance.iter().enumerate() {
        let comma = if i + 1 < defs.balance.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"key\": {}, \"max\": {}, \"min\": {}, \"value\": {} }}{comma}\n",
            json_escape(&b.key),
            b.max,
            b.min,
            b.value
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"bodies\": [\n");
    for (i, b) in defs.bodies.iter().enumerate() {
        let comma = if i + 1 < defs.bodies.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"family\": {}, \"id\": {}, \"key\": {}, \"pool\": {}, \"sheet\": {} }}{comma}\n",
            json_escape(b.family.as_str()),
            b.id,
            json_escape(&b.key),
            json_escape(b.pool.as_str()),
            json_escape(&b.sheet)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"eyes\": [\n");
    for (i, e) in defs.eyes.iter().enumerate() {
        let comma = if i + 1 < defs.eyes.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"family\": {}, \"id\": {}, \"key\": {}, \"pool\": {}, \"sheet\": {} }}{comma}\n",
            json_escape(e.family.as_str()),
            e.id,
            json_escape(&e.key),
            json_escape(e.pool.as_str()),
            json_escape(&e.sheet)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"hairstyles\": [\n");
    for (i, h) in defs.hairstyles.iter().enumerate() {
        let comma = if i + 1 < defs.hairstyles.len() {
            ","
        } else {
            ""
        };
        out.push_str(&format!(
            "    {{ \"color\": {}, \"family\": {}, \"id\": {}, \"key\": {}, \"rare\": {}, \"sheet\": {}, \"style\": {} }}{comma}\n",
            h.color,
            json_escape(h.family.as_str()),
            h.id,
            json_escape(&h.key),
            h.rare,
            json_escape(&h.sheet),
            h.style
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"outfits\": [\n");
    for (i, o) in defs.outfits.iter().enumerate() {
        let comma = if i + 1 < defs.outfits.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"family\": {}, \"hides_hairstyle\": {}, \"id\": {}, \"key\": {}, \"pool\": {}, \"sheet\": {} }}{comma}\n",
            json_escape(o.family.as_str()),
            o.hides_hairstyle,
            o.id,
            json_escape(&o.key),
            json_escape(o.pool.as_str()),
            json_escape(&o.sheet)
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"accessories\": [\n");
    for (i, a) in defs.accessories.iter().enumerate() {
        let comma = if i + 1 < defs.accessories.len() {
            ","
        } else {
            ""
        };
        out.push_str(&format!(
            "    {{ \"family\": {}, \"id\": {}, \"key\": {}, \"pool\": {}, \"sheet\": {}, \"slot\": {} }}{comma}\n",
            json_escape(a.family.as_str()),
            a.id,
            json_escape(&a.key),
            json_escape(a.pool.as_str()),
            json_escape(&a.sheet),
            json_escape(a.slot.as_str())
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"appearance_layouts\": [\n");
    for (i, l) in defs.appearance_layouts.iter().enumerate() {
        let comma = if i + 1 < defs.appearance_layouts.len() {
            ","
        } else {
            ""
        };
        let rows: Vec<String> = l
            .rows
            .iter()
            .map(|r| {
                format!(
                    "{{ \"animation\": {}, \"frames_per_direction\": {}, \"row\": {} }}",
                    json_escape(&r.animation),
                    r.frames_per_direction,
                    r.row
                )
            })
            .collect();
        let accepted_sizes: Vec<String> = l
            .accepted_sizes
            .iter()
            .map(|(w, h)| format!("{{ \"height\": {h}, \"width\": {w} }}"))
            .collect();
        out.push_str(&format!(
            "    {{ \"accepted_sizes\": [{}], \"cell_height\": {}, \"cell_width\": {}, \"directions\": {}, \"family\": {}, \"id\": {}, \"key\": {}, \"rows\": [{}] }}{comma}\n",
            accepted_sizes.join(", "),
            l.cell_height,
            l.cell_width,
            json_str_array(&l.directions),
            json_escape(l.family.as_str()),
            l.id,
            json_escape(&l.key),
            rows.join(", ")
        ));
    }
    out.push_str("  ],\n");

    out.push_str("  \"uniforms\": [\n");
    for (i, u) in defs.uniforms.iter().enumerate() {
        let comma = if i + 1 < defs.uniforms.len() { "," } else { "" };
        out.push_str(&format!(
            "    {{ \"accessory\": {}, \"id\": {}, \"key\": {}, \"outfit\": {}, \"profession\": {} }}{comma}\n",
            fmt_opt_str_json(&u.accessory),
            u.id,
            json_escape(&u.key),
            fmt_opt_str_json(&u.outfit),
            json_escape(&u.profession)
        ));
    }
    out.push_str("  ]\n");

    out.push_str("}\n");
    out
}

/// The append-only `kind id key` manifest `tools/defs-build/goldens/
/// defs-manifest.golden` pins -- balance excluded (Tim's direction: it
/// carries no id in this story). Grouped by kind in the same fixed order
/// as `emit_rust`, sorted by id within each kind (never by key, so a
/// rename never reorders these lines and never reads as a renumbering).
pub fn emit_id_manifest(defs: &Defs) -> String {
    let mut lines = Vec::new();
    let mut objects = defs.objects.clone();
    objects.sort_by_key(|o| o.id);
    for o in &objects {
        lines.push(format!("object {} {}", o.id, o.key));
    }
    let mut items = defs.items.clone();
    items.sort_by_key(|i| i.id);
    for i in &items {
        lines.push(format!("item {} {}", i.id, i.key));
    }
    let mut recipes = defs.recipes.clone();
    recipes.sort_by_key(|r| r.id);
    for r in &recipes {
        lines.push(format!("recipe {} {}", r.id, r.key));
    }
    let mut professions = defs.professions.clone();
    professions.sort_by_key(|p| p.id);
    for p in &professions {
        lines.push(format!("profession {} {}", p.id, p.key));
    }
    let mut chains = defs.chains.clone();
    chains.sort_by_key(|c| c.id);
    for c in &chains {
        lines.push(format!("chain {} {}", c.id, c.key));
    }
    let mut bodies = defs.bodies.clone();
    bodies.sort_by_key(|b| b.id);
    for b in &bodies {
        lines.push(format!("body {} {}", b.id, b.key));
    }
    let mut eyes = defs.eyes.clone();
    eyes.sort_by_key(|e| e.id);
    for e in &eyes {
        lines.push(format!("eyes {} {}", e.id, e.key));
    }
    let mut hairstyles = defs.hairstyles.clone();
    hairstyles.sort_by_key(|h| h.id);
    for h in &hairstyles {
        lines.push(format!("hairstyle {} {}", h.id, h.key));
    }
    let mut outfits = defs.outfits.clone();
    outfits.sort_by_key(|o| o.id);
    for o in &outfits {
        lines.push(format!("outfit {} {}", o.id, o.key));
    }
    let mut accessories = defs.accessories.clone();
    accessories.sort_by_key(|a| a.id);
    for a in &accessories {
        lines.push(format!("accessory {} {}", a.id, a.key));
    }
    let mut appearance_layouts = defs.appearance_layouts.clone();
    appearance_layouts.sort_by_key(|l| l.id);
    for l in &appearance_layouts {
        lines.push(format!("appearance_layout {} {}", l.id, l.key));
    }
    let mut uniforms = defs.uniforms.clone();
    uniforms.sort_by_key(|u| u.id);
    for u in &uniforms {
        lines.push(format!("uniform {} {}", u.id, u.key));
    }
    let mut text = lines.join("\n");
    text.push('\n');
    text
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::*;

    fn sample() -> Defs {
        Defs {
            objects: vec![ObjectDef {
                id: 1,
                key: "trash_bin".into(),
                name: "Trash Bin".into(),
                layer: 2,
                sprite: SpriteRect {
                    sheet: "ModernTileset/Pier_Bin_1.png".into(),
                    x: 0,
                    y: 0,
                    w: 16,
                    h: 16,
                },
                width: 1,
                height: 1,
                collider: Some(ColliderRect {
                    x0: 4,
                    y0: 4,
                    x1: 12,
                    y1: 12,
                }),
                interact_at: Some(ColliderRect {
                    x0: 0,
                    y0: 16,
                    x1: 16,
                    y1: 32,
                }),
                window: false,
            }],
            items: vec![ItemDef {
                id: 1,
                key: "bottle".into(),
            }],
            recipes: vec![RecipeDef {
                id: 1,
                key: "bottle_recycling".into(),
                inputs: vec!["bottle".into()],
                outputs: vec![],
            }],
            professions: vec![ProfessionDef {
                id: 1,
                key: "sanitation_worker".into(),
            }],
            chains: vec![ChainDef {
                id: 1,
                key: "plastic_bottle".into(),
                links: vec!["sanitation_worker".into()],
            }],
            balance: vec![BalanceDef {
                key: "citizen.bar_decay.rest".into(),
                value: 10,
                min: 0,
                max: 100,
            }],
            bodies: vec![BodyDef {
                id: 1,
                key: "body_01".into(),
                family: Family::Adult,
                sheet: "ModernTileset/Bodies/Body_01.png".into(),
                pool: Pool::Civilian,
            }],
            eyes: vec![EyesDef {
                id: 1,
                key: "eyes_01".into(),
                family: Family::Adult,
                sheet: "ModernTileset/Eyes/Eyes_01.png".into(),
                pool: Pool::Civilian,
            }],
            hairstyles: vec![HairstyleDef {
                id: 1,
                key: "hairstyle_01_01".into(),
                family: Family::Adult,
                sheet: "ModernTileset/Hairstyles/Hairstyle_01_01.png".into(),
                style: 1,
                color: 1,
                rare: false,
            }],
            outfits: vec![OutfitDef {
                id: 1,
                key: "outfit_01_01".into(),
                family: Family::Adult,
                sheet: "ModernTileset/Outfits/Outfit_01_01.png".into(),
                pool: Pool::Civilian,
                hides_hairstyle: false,
            }],
            accessories: vec![AccessoryDef {
                id: 1,
                key: "accessory_06_policeman_hat_01".into(),
                family: Family::Adult,
                sheet: "ModernTileset/Accessories/Accessory_06_Policeman_Hat_01.png".into(),
                pool: Pool::RoleOnly,
                slot: Slot::Head,
            }],
            appearance_layouts: vec![AppearanceLayoutDef {
                id: 1,
                key: "adult".into(),
                family: Family::Adult,
                cell_width: 16,
                cell_height: 32,
                directions: vec!["right".into(), "up".into(), "left".into(), "down".into()],
                rows: vec![AppearanceLayoutRowDef {
                    animation: "idle".into(),
                    row: 1,
                    frames_per_direction: 6,
                }],
                accepted_sizes: vec![(896, 656), (927, 656)],
            }],
            uniforms: vec![UniformDef {
                id: 1,
                key: "sanitation_worker_uniform".into(),
                profession: "sanitation_worker".into(),
                outfit: None,
                accessory: Some("accessory_06_policeman_hat_01".into()),
            }],
        }
    }

    #[test]
    fn emit_rust_opens_with_the_generated_header_and_carries_the_version() {
        let out = emit_rust(&sample(), "abc123");
        assert!(out.starts_with(GENERATED_HEADER_RUST));
        assert!(out.contains("pub const DEFS_VERSION: &str = \"abc123\";"));
        assert!(out.contains(
            "ObjectDef { id: 1, key: \"trash_bin\", name: \"Trash Bin\", layer: 2, sprite: SpriteRect { sheet: \"ModernTileset/Pier_Bin_1.png\", x: 0, y: 0, w: 16, h: 16 }, width: 1, height: 1, collider: Some(ColliderRect { x0: 4, y0: 4, x1: 12, y1: 12 }), interact_at: Some(ColliderRect { x0: 0, y0: 16, x1: 16, y1: 32 }), window: false }"
        ));
        assert!(out.contains("pub const COLLIDER_SUBCELLS_PER_CELL: i32 = 16;"));
        assert!(out.contains("pub const INTERACT_AT_MAX_REACH_CELLS: i32 = 2;"));
        assert!(out.contains("pub const MAX_FOOTPRINT_CELLS: i32 = 8;"));
        assert!(!out.contains('\r'));
    }

    #[test]
    fn emit_rust_renders_an_absent_collider_as_none() {
        let mut defs = sample();
        defs.objects[0].collider = None;
        let out = emit_rust(&defs, "abc123");
        assert!(out.contains("collider: None"));
    }

    #[test]
    fn emit_rust_renders_an_absent_interact_at_as_none() {
        let mut defs = sample();
        defs.objects[0].interact_at = None;
        let out = emit_rust(&defs, "abc123");
        assert!(out.contains("interact_at: None"));
    }

    #[test]
    fn emit_json_renders_an_interact_at_object_and_null_for_absent() {
        let mut defs = sample();
        let out = emit_json(&defs, "v1");
        assert!(out.contains("\"interact_at\": { \"x0\": 0, \"y0\": 16, \"x1\": 16, \"y1\": 32 }"));
        assert!(out.contains("\"interact_at_max_reach_cells\": 2"));
        defs.objects[0].interact_at = None;
        let out = emit_json(&defs, "v1");
        assert!(out.contains("\"interact_at\": null"));
    }

    #[test]
    fn emit_json_opens_with_generated_by_then_defs_version() {
        let out = emit_json(&sample(), "abc123");
        let lines: Vec<&str> = out.lines().collect();
        assert!(lines[1].contains("\"generated_by\""));
        assert!(lines[2].contains("\"defs_version\": \"abc123\""));
        assert!(lines[3].contains("\"collider_subcells_per_cell\": 16"));
        assert!(lines[4].contains("\"interact_at_max_reach_cells\": 2"));
        assert!(lines[5].contains("\"max_footprint_cells\": 8"));
        assert!(!out.contains('\r'));
    }

    #[test]
    fn emit_json_renders_a_collider_object_and_null_for_absent() {
        let mut defs = sample();
        let out = emit_json(&defs, "v1");
        assert!(out.contains("\"collider\": { \"x0\": 4, \"y0\": 4, \"x1\": 12, \"y1\": 12 }"));
        defs.objects[0].collider = None;
        let out = emit_json(&defs, "v1");
        assert!(out.contains("\"collider\": null"));
    }

    #[test]
    fn emit_json_renders_name_layer_and_sprite() {
        let out = emit_json(&sample(), "v1");
        assert!(out.contains("\"layer\": 2"));
        assert!(out.contains("\"name\": \"Trash Bin\""));
        assert!(out.contains(
            "\"sprite\": { \"sheet\": \"ModernTileset/Pier_Bin_1.png\", \"x\": 0, \"y\": 0, \"w\": 16, \"h\": 16 }"
        ));
    }

    #[test]
    fn emit_rust_renders_name_layer_and_sprite() {
        let out = emit_rust(&sample(), "v1");
        assert!(out.contains("name: \"Trash Bin\""));
        assert!(out.contains("layer: 2"));
        assert!(out.contains(
            "sprite: SpriteRect { sheet: \"ModernTileset/Pier_Bin_1.png\", x: 0, y: 0, w: 16, h: 16 }"
        ));
    }

    #[test]
    fn emit_json_renders_the_window_flag() {
        let mut defs = sample();
        let out = emit_json(&defs, "v1");
        assert!(out.contains("\"window\": false"));
        defs.objects[0].window = true;
        let out = emit_json(&defs, "v1");
        assert!(out.contains("\"window\": true"));
    }

    #[test]
    fn emit_json_is_valid_enough_to_round_trip_by_eye_every_kind_present() {
        let out = emit_json(&sample(), "v1");
        for key in [
            "\"objects\"",
            "\"items\"",
            "\"recipes\"",
            "\"professions\"",
            "\"chains\"",
            "\"balance\"",
            "\"bodies\"",
            "\"eyes\"",
            "\"hairstyles\"",
            "\"outfits\"",
            "\"accessories\"",
            "\"appearance_layouts\"",
            "\"uniforms\"",
        ] {
            assert!(out.contains(key), "missing {key} in {out}");
        }
    }

    #[test]
    fn emit_rust_renders_every_appearance_kind() {
        let out = emit_rust(&sample(), "abc123");
        assert!(out.contains("pub enum Family"));
        assert!(out.contains("pub enum Pool"));
        assert!(out.contains(
            "BodyDef { id: 1, key: \"body_01\", family: Family::Adult, sheet: \"ModernTileset/Bodies/Body_01.png\", pool: Pool::Civilian }"
        ));
        assert!(out.contains("EyesDef { id: 1, key: \"eyes_01\""));
        assert!(out.contains("HairstyleDef { id: 1, key: \"hairstyle_01_01\""));
        assert!(out.contains("OutfitDef { id: 1, key: \"outfit_01_01\""));
        assert!(out.contains("pool: Pool::Civilian"));
        assert!(out.contains("AccessoryDef { id: 1"));
        assert!(out.contains("pool: Pool::RoleOnly"));
        assert!(out.contains("slot: Slot::Head"));
        assert!(out.contains("AppearanceLayoutDef { id: 1, key: \"adult\""));
        assert!(out.contains(
            "AppearanceLayoutRowDef { animation: \"idle\", row: 1, frames_per_direction: 6 }"
        ));
        assert!(out.contains("accepted_sizes: &[(896, 656), (927, 656)]"));
        assert!(out.contains("pub struct BodyDef {\n    pub id: u16,"));
        assert!(out.contains(
            "UniformDef { id: 1, key: \"sanitation_worker_uniform\", profession: \"sanitation_worker\", outfit: None, accessory: Some(\"accessory_06_policeman_hat_01\") }"
        ));
    }

    #[test]
    fn emit_id_manifest_includes_every_appearance_kind() {
        let manifest = emit_id_manifest(&sample());
        assert!(manifest.contains("body 1 body_01"));
        assert!(manifest.contains("eyes 1 eyes_01"));
        assert!(manifest.contains("hairstyle 1 hairstyle_01_01"));
        assert!(manifest.contains("outfit 1 outfit_01_01"));
        assert!(manifest.contains("accessory 1 accessory_06_policeman_hat_01"));
        assert!(manifest.contains("appearance_layout 1 adult"));
        assert!(manifest.contains("uniform 1 sanitation_worker_uniform"));
    }

    #[test]
    fn emit_id_manifest_excludes_balance_and_sorts_by_id_within_kind() {
        let mut defs = sample();
        defs.objects.push(ObjectDef {
            id: 0,
            key: "aardvark".into(),
            name: "Aardvark".into(),
            layer: 2,
            sprite: SpriteRect {
                sheet: "ModernTileset/Pier_Bin_1.png".into(),
                x: 0,
                y: 0,
                w: 16,
                h: 16,
            },
            width: 1,
            height: 1,
            collider: None,
            interact_at: None,
            window: false,
        });
        let manifest = emit_id_manifest(&defs);
        let lines: Vec<&str> = manifest.lines().collect();
        assert_eq!(lines[0], "object 0 aardvark");
        assert_eq!(lines[1], "object 1 trash_bin");
        assert!(!manifest.contains("balance"));
    }
}
