[[appearance_layout]]
id = 1
key = "adult"
family = "adult"
cell_width = 16
cell_height = 32
directions = ["right", "up", "left", "down"]
rows = [
  { animation = "idle", row = 1, frames_per_direction = 6 },
  { animation = "walk", row = 2, frames_per_direction = 6 },
]

[[appearance_layout]]
id = 2
key = "kid"
family = "kid"
cell_width = 16
cell_height = 32
directions = ["right", "up", "left", "down"]
rows = [
  { animation = "idle", row = 1, frames_per_direction = 6 },
  { animation = "walk", row = 2, frames_per_direction = 6 },
]

