//! Story 1.10: the demo scene's street crowd must show what
//! `sim::appearance::generate` actually produces, never a hand-rolled
//! index walk over each part list -- so this crate is the one source of
//! every tuple the demo renders, committed as a JSON fixture the client
//! fetches at runtime, exactly like `defs.json`. Checked here against
//! fresh regeneration, the same "committed artefact matches its own
//! generator" idiom as `tools/defs-build/tests/defs_dump.rs`: never
//! regenerated by this test, a mismatch is exactly the moment a human
//! must look.
//!
//! Lives outside `server/` (a standalone crate depending on `sim`, this
//! crate's own `Cargo.toml` explains why): `scripts/ci/
//! check-no-shared-code.sh` greps every file under `server/` for the
//! literal string this fixture's own path contains.

use sim::appearance::{generate, live_catalogue};
use sim::generated::defs::Family;

/// A fixed, deterministic citizen id per row -- 1..=52, both families, a
/// generous enough pool to draw a street crowd from. Never the citizen
/// ids a real spawn story will use; this crate has no concept of a live
/// citizen yet, only of what `generate` returns for an id.
const CITIZEN_IDS: std::ops::RangeInclusive<u64> = 1..=52;

const FIXTURE_PATH: &str = "../../client/public/demo-citizens.json";

fn family_str(family: Family) -> &'static str {
    match family {
        Family::Adult => "adult",
        Family::Kid => "kid",
    }
}

fn canonical_json() -> String {
    let catalogue = live_catalogue();
    let mut out = String::new();
    out.push_str("{\n");
    out.push_str(
        "  \"generated_by\": \"tools/demo-citizens-build/tests/demo_citizens_fixture.rs\",\n",
    );
    out.push_str("  \"rows\": [\n");
    let mut rows: Vec<String> = Vec::new();
    for id in CITIZEN_IDS {
        for family in [Family::Adult, Family::Kid] {
            let a = generate(id, family, &catalogue);
            rows.push(format!(
                "    {{ \"id\": {id}, \"family\": {:?}, \"body\": {}, \"eyes\": {}, \"outfit\": {}, \"hairstyle\": {}, \"accessory\": {} }}",
                family_str(family),
                a.body,
                a.eyes,
                a.outfit,
                a.hairstyle,
                a.accessory
            ));
        }
    }
    out.push_str(&rows.join(",\n"));
    out.push_str("\n  ]\n}\n");
    out
}

#[test]
fn matches_the_committed_demo_citizens_fixture() {
    let expected = canonical_json();
    let actual = std::fs::read_to_string(FIXTURE_PATH)
        .unwrap_or_else(|e| panic!("demo_citizens_fixture: could not read {FIXTURE_PATH}: {e}"));
    assert_eq!(
        actual, expected,
        "{FIXTURE_PATH} does not match sim::appearance::generate's own live output -- \
         regenerate it (this test's own module doc says how) whenever `defs/appearance/` \
         or the generator's algorithm changes"
    );
}
